---
title: "BRAF"
output: html_document
---

```{r}
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggforce)
theme_set(theme_bw(18))

KnownTarget_predictions_v2= readRDS('../Data/KnownTarget_predictions_v2.RDS')
clinical_data= read.csv('../Data/biomarkers.csv')
```


```{r}
head(KnownTarget_predictions_v2)
names(KnownTarget_predictions_v2)[c(2,3)]= c('Known_MaxTargetName','knownTarget_bestCorr')

BRAF_drug= filter(KnownTarget_predictions_v2, grepl('BRAF',Known_MaxTargetName)) %>% distinct(drugName, .keep_all= T)
hist(BRAF_drug$knownTarget_bestCorr)
```

```{r fig.width=4,fig.height=2}
df2plot_BRAF_distribution= BRAF_drug
ggplot(df2plot_BRAF_distribution, aes(x= knownTarget_bestCorr, y= interaction_strength, color= knownTarget_bestCorr > 0.2))+
  geom_jitter()+
   geom_text_repel(data = df2plot_BRAF_distribution[df2plot_BRAF_distribution$knownTarget_bestCorr >0.2,], 
                   aes(label = paste(Known_MaxTargetName,":",drugName)), max.overlaps = 14, 
                  size= 3)+
  theme_bw(base_size = 15)+
  xlab('Specificity Score')+
  ylab('interaction pval')+
  labs(x= 'Specificity Score', y = 'interaction pval', colour = "known Target\nspecificity score > 0.2") 

```

```{r fig.width=4,fig.height=2}
colnames(clinical_data)[3] = 'drugName'
df2plot_join_with_launch_data= left_join(df2plot_BRAF_distribution[, c('drugName','Known_MaxTargetName','knownTarget_bestCorr', 'drugBroadID', 'PredictedRank')], 
                                         clinical_data[clinical_data$drugName %in% intersect(BRAF_drug$drugName, clinical_data$drugName),c('drugName','dose','phase')], by= 'drugName')

df2plot_join_with_launch_data = df2plot_join_with_launch_data %>% mutate(phase = replace(phase, phase == 'Phase 1/Phase 2', 'Phase 2'))
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Preclinical'] = 1
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 1'] = 2
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 2'] = 3
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 3'] = 4
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Launched'] = 5

combnations= combn(unique(df2plot_join_with_launch_data$phase),2, simplify = F)
ggplot(df2plot_join_with_launch_data, aes(x= reorder(factor(phase),clinical_stage), 
                                          y= knownTarget_bestCorr,
                                          color= clinical_stage))+
  geom_boxplot()+
  stat_compare_means(comparisons = combnations)+
  theme_bw(base_size = 18)+
  ylab('Specificity Score')+
  xlab('stage')
```
<!--BRAF generation-->
```{r}

```


