---
title: "R Notebook"
output: html_notebook
---

<!-- Find other BTK-ibrutinib like drugs -->
```{r}
interaction_Features_noduplicated=interaction_Features[!duplicated(interaction_Features)]
# interaction_Features[grep('ibrutinib',names(interaction_Features))]
interaction_Features_df=as.data.frame(do.call(rbind, interaction_Features_noduplicated))
interaction_Features_df=na.omit(interaction_Features_df)
interaction_strength_df_ordered=interaction_Features_df[order(interaction_Features_df$Estimate),]
interaction_strength_df_ordered[grep('ibrutinib',rownames(interaction_strength_df_ordered)),]
other_drugsLike_ibrutinib=rownames(interaction_strength_df_ordered[interaction_strength_df_ordered$`Pr(>|t|)` < 0.05 & 
                                  interaction_strength_df_ordered$Estimate < -1,])
```


```{r}
other_drugsLike_ibrutinib_id=stripall2match(KnownTarget_predictions$drugName) %in% stripall2match(other_drugsLike_ibrutinib)
KnownTarget_predictions[other_drugsLike_ibrutinib_id ,]
```



