---
title: "EGFR"
output: html_document
---
<!-- DKS score vs Clinical advancement -->
```{r}
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggforce)
theme_set(theme_bw(18))

KnownTarget_predictions_v2= readRDS('../Data/KnownTarget_predictions_v2.RDS')

clinical_data= read.csv('../Data/biomarkers.csv')
```


```{r}
head(KnownTarget_predictions_v2)
names(KnownTarget_predictions_v2)[c(2,3)]= c('Known_MaxTargetName','knownTarget_bestCorr')

head(sort(table(KnownTarget_predictions_v2$Known_MaxTargetName), decreasing = T),20)
EGFR_drug= filter(KnownTarget_predictions_v2, grepl('EGFR',Known_MaxTargetName)) %>% distinct(drugName, .keep_all= T)
hist(EGFR_drug$knownTarget_bestCorr)
```

```{r fig.width=4,fig.height=2}
df2plot_EGFR_distribution= EGFR_drug
ggplot(df2plot_EGFR_distribution, aes(x= knownTarget_bestCorr, y=BestTargetCorr , color= knownTarget_bestCorr > 0.1))+
  geom_jitter()+
   geom_text_repel(data = df2plot_EGFR_distribution[df2plot_EGFR_distribution$knownTarget_bestCorr >0.1,], 
                   aes(label = paste(Known_MaxTargetName,":",drugName)), 
                  size= 3)+
  theme_bw(base_size = 15)+
  xlab('Specificity Score')+
  ylab('interaction pval')+
  labs(x= 'Specificity Score', y = 'interaction pval', colour = "known Target\nspecificity score > 0.1") 
```

```{r}
df2plot_EGFR_distribution= EGFR_drug
colnames(clinical_data)[3] = 'drugName'
df2plot_join_with_launch_data= left_join(df2plot_EGFR_distribution[, c('drugName','Known_MaxTargetName','knownTarget_bestCorr', 'drugBroadID', 'PredictedRank')], 
                                         clinical_data[clinical_data$drugName %in% intersect(EGFR_drug$drugName, clinical_data$drugName),c('drugName','dose','phase')], by= 'drugName')

df2plot_join_with_launch_data= df2plot_join_with_launch_data[!(is.na(df2plot_join_with_launch_data$phase)),]
df2plot_join_with_launch_data = df2plot_join_with_launch_data %>% mutate(phase = replace(phase, phase == 'Phase 1/Phase 2', 'Phase 2'))
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Preclinical'] = 1
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 1'] = 2
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 2'] = 3
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Phase 3'] = 4
df2plot_join_with_launch_data$clinical_stage[df2plot_join_with_launch_data$phase== 'Launched'] = 5
```


```{r fig.width=4,fig.height=2}
# df2_plot_mean= df2plot_join_with_launch_data %>% group_by(phase, clinical_stage) %>% summarise(knownTarget_bestCorr = mean(knownTarget_bestCorr))
# factor(df2_plot_mean$phase)

### creating combinations for pvals
combnations= combn(unique(df2plot_join_with_launch_data$phase),2, simplify = F)

figure_2E= ggplot(df2plot_join_with_launch_data, aes(x= reorder(factor(phase),clinical_stage), 
                                          y= knownTarget_bestCorr,
                                          color= clinical_stage))+
  geom_boxplot()+
  stat_compare_means(comparisons = combnations)+
  theme_bw(base_size = 15)+
  stat_smooth(method = 'lm', se= T, level = 0.8,
              span= 1, aes(group= 1), linetype= 'dotted', size= 0.8)+
   # theme(axis.title.y=element_blank())+
  ylab('DKS Score')+
  xlab('EGFR Clinical Stages')
ggsave('../result/EGFR_specificity_score_phases.png',figure_2E,
       width = 8, height = 5, units = 'in', dpi = 300)
```

<!--HDAC1-->
```{r fig.width=4,fig.height=2}
### creating combinations for pvals
combnations= combn(unique(df2plot_join_with_launch_data$phase),2, simplify = F)

figure_2F= ggplot(df2plot_join_with_launch_data, aes(x= reorder(factor(phase),clinical_stage), 
                                          y= knownTarget_bestCorr,
                                          color= clinical_stage))+
  geom_boxplot()+
  stat_compare_means(comparisons = combnations)+
  theme_bw(base_size = 15)+
  stat_smooth(method = 'lm', se= T, level = 0.8,
              span= 1, aes(group= 1), linetype= 'dotted', size= 0.8)+
   # theme(axis.title.y=element_blank())+
  ylab('DKS Score')+
  xlab('HDAC1 Clinical Stages')
ggsave('../result/HDAC1_specificity_score_phases.png',figure_3A,
       width = 8, height = 5, units = 'in', dpi = 300)
```

```{r fig.width=4,fig.height=2}
### creating combinations for pvals
combnations= combn(unique(df2plot_join_with_launch_data$phase),2, simplify = F)

figure_2G= ggplot(df2plot_join_with_launch_data, aes(x= reorder(factor(phase),clinical_stage), 
                                          y= knownTarget_bestCorr,
                                          color= clinical_stage))+
  geom_boxplot()+
  stat_compare_means(comparisons = combnations)+
  theme_bw(base_size = 15)+
  stat_smooth(method = 'lm', se= T, level = 0.8,
              span= 1, aes(group= 1), linetype= 'dotted', size= 0.8)+
   # theme(axis.title.y=element_blank())+
  ylab('DKS Score')+
  xlab('MAP2K1 Clinical Stages')
ggsave('../result/MAP2K1_specificity_score_phases.png',figure_2G,
       width = 8, height = 5, units = 'in', dpi = 300)
```


```{r}
# Figure_ERBB2
# Figure_EGFR 
# Figure_MAP2K1
# Figure_2_HDAC1 
# Figure_2_BCL2
Figure2_EFG= ggarrange(figure_2E,
                       figure_2F,
                       figure_2G,
                       labels = c('E','F','G'), 
                        ncol = 3, common.legend = T, legend = 'top')
ggsave(Figure2_EFG, filename = '../result/Figure2_EFG_v4.png',
       width = 14, height =4)
ggsave(Figure2_EFG, filename = '../result/Figure2_EFG_v4.pdf',
       width = 14, height = 4)

```

<!--EGFR generation-->
```{r}
first_gen= c('gefitinib', 'erlotinib','icotinib')
second_gen= c('afatinib','dacomitinib')
third_gen =c('osimertinib',
             'rociletinib',
             'nazartinib','EGF816',
             'mavelertinib', 'PF-06747775',
             'avitinib',
             'lazertinib', 'YH25448','GNS-1480',
             'olmutinib','HM61713',
             'Naquotinib','ASP8273')

intersect(df2plot_EGFR_distribution$drugName, first_gen)

df2plot_EGFR_generation= df2plot_EGFR_distribution[df2plot_EGFR_distribution$drugName %in% c(first_gen, second_gen, third_gen),]
df2plot_EGFR_generation$drug_generation= ifelse(df2plot_EGFR_generation$drugName %in% first_gen, '1st_Gen',
                                                ifelse(df2plot_EGFR_generation$drugName %in% second_gen, '2nd_Gen',
                                                       '3rd_Gen'))
ggplot(df2plot_EGFR_generation, aes(x= drug_generation, y= knownTarget_bestCorr, color= drug_generation))+
  geom_point()+
   geom_text_repel(data = df2plot_EGFR_generation, 
                   aes(label = paste(Known_MaxTargetName,":",drugName)), 
                  size= 3)+
  theme_bw(base_size = 15)+
  labs(x= 'Generation', y = 'Known target specificity Score', colour = "EGFR generation") 
```

<!--regression for egfr-->
```{r}
table(df2plot_join_with_launch_data$Known_MaxTargetName)

EGFR_launched_relation= lm(clinical_stage~ knownTarget_bestCorr, data = df2plot_join_with_launch_data)
summary(EGFR_launched_relation)
effect_plot(EGFR_launched_relation, pred = knownTarget_bestCorr, interval = TRUE, plot.points = TRUE,
            jitter = 0.05)

cor.test(df2plot_join_with_launch_data$knownTarget_bestCorr, df2plot_join_with_launch_data$clinical_stage)
```


<!--repeating this lauched data check on all drugs and targets-->
```{r fig.width=4,fig.height=2}
df2plot_all_launch_data = KnownTarget_predictions_v2$drugName %>% distinct(drugName, .keep_all= T)

df2plot_all_launch_data = df2plot_all_launch_data[!is.na(df2plot_all_launch_data$phase),]
df2plot_all_launch_data = df2plot_all_launch_data[!(df2plot_all_launch_data$phase == 'Withdrawn'),]

df2plot_all_launch_data = df2plot_all_launch_data %>% mutate(phase = replace(phase, phase == 'Phase 1/Phase 2', 'Phase 2'))
df2plot_all_launch_data = df2plot_all_launch_data %>% mutate(phase = replace(phase, phase == 'Phase 2/Phase 3', 'Phase 3'))
# df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Withdrawn'] = 1
df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Preclinical'] = 1
df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Phase 1'] = 2
df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Phase 2'] = 3
df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Phase 3'] = 4
df2plot_all_launch_data$clinical_stage[df2plot_all_launch_data$phase== 'Launched'] = 5

# ## combination
# combnations= combn(unique(df2plot_all_launch_data$phase),2, simplify = F)
# ggplot((df2plot_all_launch_data), aes(x= reorder(factor(phase),knownTarget_bestCorr), 
#                                           y= knownTarget_bestCorr,
#                                           color= clinical_stage))+
#   geom_boxplot()+
#   stat_compare_means(comparisons = combnations)+
#   stat_summary(fun=mean, geom="point", shape=20, size=2, color="red", fill="red")+
#   theme_bw(base_size = 12)+
#   ylab('Specificity Score')+
#   xlab('stage')
```

<!--groupby-->
```{r}
broad_id_targeted_therapy= onTarget$drugCategory[onTarget$drugCategory$drug_category == 'targeted cancer', c('broad_id_trimmed')]

df2plot_targeted_launched = df2plot_all_launch_data[df2plot_all_launch_data$drugBroadID %in% broad_id_targeted_therapy, ] 

df2plot_boxplot_aggregate= df2plot_targeted_launched[, c('Known_MaxTargetName', 'knownTarget_bestCorr', 'phase','clinical_stage')] %>% group_by(Known_MaxTargetName, phase) %>% 
  summarise(med_cor= median(knownTarget_bestCorr),.groups = 'drop')


# df2plot_boxplot_aggregate$phase=factor(df2plot_boxplot_aggregate$phase)
# levels(df2plot_boxplot_aggregate$phase)= levels(df2plot_boxplot_aggregate$phase)
# # df2plot_boxplot_aggregate$phase=fct_rev(df2plot_boxplot_aggregate$phase)
# ## combination
# combnations= combn(unique(df2plot_boxplot_aggregate$phase),2, simplify = F)
# 
# ggplot(df2plot_boxplot_aggregate, aes(x= reorder(factor(phase),med_cor),  y= med_cor))+
#   geom_boxplot()+
#   # stat_compare_means(comparisons = combnations)+
#   # stat_summary(fun=mean, geom="point", shape=20, size=2, color="red", fill="red")+
#   theme_bw(base_size = 12)+
#   ylab('Specificity Score')+
#   xlab('stage')
```

```{r}
most_freq_targets=names(which(table(df2plot_boxplot_aggregate$Known_MaxTargetName) >3))

df2plot_all_launch_data[df2plot_all_launch_data$Known_MaxTargetName %in% most_freq_targets[13],]
linear_model_targets= as.data.frame(t(sapply(1:length(most_freq_targets), function (x)
  summary(lm(clinical_stage~ knownTarget_bestCorr, 
             data = df2plot_all_launch_data[df2plot_all_launch_data$Known_MaxTargetName %in% most_freq_targets[x],]
             ))$coefficients[2,c(1,4)]
  )),row.names = most_freq_targets)

colnames(linear_model_targets)[2] = 'Pvalue'
linear_model_targets$fdr_pval= fdrcorr(linear_model_targets$Pvalue)
linear_model_targets[order(linear_model_targets$Estimate, decreasing = T),]

```


<!--regression for all drug_target Which have alleast 3 phase info-->
```{r}
all_target_launched_relation= lm(clinical_stage~ knownTarget_bestCorr + as.factor(Known_MaxTargetName), data =df2plot_all_launch_data)
summary(all_target_launched_relation)
# 
# table(df2plot_targeted_launched$clinical_stage)
targeted_launched_relationship= lm(clinical_stage~ knownTarget_bestCorr + as.factor(Known_MaxTargetName), data =df2plot_targeted_launched)
summary(targeted_launched_relationship)
# 
# library(jtools)
# effect_plot(targeted_launched_relationship, pred = knownTarget_bestCorr, interval = TRUE, plot.points = TRUE, 
#             jitter = 0.05)
```

```{r}

combnations= combn(unique(boxplot_most_frequent_target$phase),2, simplify = F)

ggplot(boxplot_most_frequent_target, aes(x= phase,  y= med_cor))+
  geom_boxplot()+
   stat_compare_means(comparisons = combnations)+
  theme_bw(base_size = 12)+
  ylab('Specificity Score')+
  xlab('stage')

```




