---
title: "R Notebook"
output: html_notebook
---

<!-- SECONDARY TARGETS SECTION-->
<!-- Chart the landscape of secondary Targets -->
```{r}
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
```

<!-- Only focus on drugs where the primary target is correct -->
```{r}
correctly_predicted=which(KnownTarget_predictions$PredictedRank<523)
```

```{r}
count_correct_direction_prop=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]<0, na.rm = T)/
  length(na.omit(KnownTarget_predictions$interaction_strength[correctly_predicted]))

count_sig_correct_direction=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]<0 &
      KnownTarget_predictions$mutation_interaction_P[correctly_predicted]<0.05, na.rm = T)
count_sig_wrong_direction=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]>0 &
      KnownTarget_predictions$mutation_interaction_P[correctly_predicted]<0.05, na.rm = T)
count_sig_correct_direction/(count_sig_correct_direction+count_sig_wrong_direction)
```

```{r}
correctly_pred_KnownTarget_predictions=KnownTarget_predictions[correctly_predicted,]
Figrue6A_data=correctly_pred_KnownTarget_predictions
Figrue6A_data$direction='+ve Interaction'
Figrue6A_data$direction[Figrue6A_data$interaction_strength<0]='-ve Interaction'
Figrue6A_data$direction[Figrue6A_data$interaction_strength<0 & 
                                  Figrue6A_data$interaction_P<0.1 ]='Sig -ve\nInteraction'

sum(Figrue6A_data$interaction_strength<0, na.rm=T)/length(na.omit(Figrue6A_data$interaction_strength))
Figrue6A <- ggplot(Figrue6A_data, aes(y=interaction_strength,
                          x= -log10(mutation_interaction_P),
                                    color=direction
                                    ))+
  geom_point()+
  theme_bw(base_size = 15)+
  labs(x='-log10(P)', y='Dependency of correlation\non expression', )+
  theme(legend.position = 'top',legend.title = element_blank())+
  guides(color=guide_legend(nrow=3,byrow=TRUE))
Figrue6A
```

```{r}
colnames(KnownTarget_predictions)[16]='KnownTarget_meanExp'
```
<!-- Proof of concept of BTK inhibitors -->
```{r}
KnownTarget_predictions[grep('BTK',KnownTarget_predictions$MaxTargetName),]
```
```{r}
GOI='BTK'; DOI='Ibrutinib'
DOI_id=KnownTarget_predictions$drugBroadID[match_stripall(DOI, KnownTarget_predictions$drugName)]
Figure6B_data=data.frame(crispr=avana_matched[GOI,],
                         drug_response=drug_matched[DOI_id,],
                         expression=factor(expression_matched[GOI,]<2, labels = c('High', 'Low')))
Figure6B <- ggplot(Figure6B_data, aes(x=crispr, y=drug_response, color=expression))+
  # geom_point()+
  stat_smooth(method = 'lm', se = T)+
  theme_bw(base_size = 12)+
  labs(x='Viability after BTK CRISPR-KO',
       y='Response to Ibrutinib',
       color='BTK\nexpression\nstatus')+
  stat_cor(label.y = c(1.2,1.4), size=6)+
  theme(legend.position = 'top')
Figure6B
```

```{r}
Figure6C_data=data.frame(Ibrutinib_Rho=corrMat[,DOI_id],
                         Ibrutinib_Rho_rank=corrMat_rank[,DOI_id],
                         Ibrutinib_Rho_P=corrMat_P[,DOI_id])
Figure6C_data$ann=''
Figure6C_data$ann[Figure6C_data$Ibrutinib_Rho>0.28]=rownames(corrMat_P)[Figure6C_data$Ibrutinib_Rho>0.28]
  
Figure6C <- ggplot(Figure6C_data, aes(y=Ibrutinib_Rho,
                                      color=Ibrutinib_Rho_rank,
                                      x= -log10(Ibrutinib_Rho_P), 
                                      label=ann))+
  geom_point()+
  # stat_smooth(method = 'lm', se = T)+
  theme_bw(base_size = 12)+
  labs(y='Correlation between gene\nKO and Ibrutinib response\nin no-BTK cell lines',
       x='-log10(P)',
       color='Rank')+
  geom_label_repel(nudge_y = c(-0.1, -0.2))+
  theme(legend.position = 'top', legend.text = element_text(size=8))
Figure6C
```

```{r}
Figure6 <-grid.arrange(Figure6B, Figure6C, Figure6A,
                       layout_matrix = matrix(c(1, 2, 3), nrow = 1,ncol = 3)
                       )
ggsave(Figure6, filename = '/Users/sinhas8/Project_TrueTarget/Results/Figure6v0.png',
       width = 14, height = 4)
ggsave(Figure6, filename = '/Users/sinhas8/Project_TrueTarget/Results/Figure6v0.pdf',
       width = 14, height = 4)
```
