---
title: "supplementary figure 7G or 8"
output: html_notebook
---

<!-- Wrongly allocated target and pathway -->
<!-- Create Alluvial Plot -->
```{r}
library(qusage)
require('ggalluvial')
hallmark_pathway=read.gmt('../Data/h.all.v7.5.1.symbols (1).gmt')
pathway_annotation=sapply(1:nrow(KnownTarget_predictions),function(y)
  na.omit(sapply(names(hallmark_pathway), function(x) match(KnownTarget_predictions$MaxTargetName[y], hallmark_pathway[[x]])))[1] )
pathway_annotation[1:10]
```
```{r}
drugs_withNo_targets=which(is.na(KnownTarget_predictions$MaxTargetName))
unknown_Targets_drugs=KnownTarget_predictions[drugs_withNo_targets,]
#current pathway
unknown_Targets_drugs$Known_Pathway='Unknown'
predicted_pathway_annotation=sapply(1:nrow(unknown_Targets_drugs),function(y)
  names(na.omit(sapply(names(hallmark_pathway), function(x) match(unknown_Targets_drugs$BestTargetName[y], hallmark_pathway[[x]])))[1]) )
unknown_Targets_drugs$predictedPathway=predicted_pathway_annotation
cond1=unknown_Targets_drugs$BestTargetCorrFDR<0.05
cond2=grepl('targeted cancer', unknown_Targets_drugs$drugCategory)
unknown_Targets_drugs_filtered=unique(unknown_Targets_drugs[cond2 & cond2,])
```


```{r}
Figure4A_data=data.frame(table(unknown_Targets_drugs_filtered$Known_Pathway, unknown_Targets_drugs_filtered$predictedPathway))
mean_corr=aggregate(unknown_Targets_drugs_filtered$BestTargetCorr,
                        by =list(unknown_Targets_drugs_filtered$Known_Pathway, unknown_Targets_drugs_filtered$predictedPathway), mean)[,3]
Figure4A_data$mean_corr=mean_corr
```

```{r}
Figure4A_data$Var2=gsub('_',' ',gsub('HALLMARK_','',Figure4A_data$Var2))
Figure4A <- ggplot(data = Figure4A_data,
       aes(axis1 = Var1, axis2 = str_wrap(Var2, 15), y = Freq)) +
  geom_alluvium(aes(fill=mean_corr)) +
  geom_stratum() +
  geom_text(stat = "stratum",
            aes(label = after_stat(stratum)), size=2) +
  scale_x_discrete(limits = c("Var1", "Var2"),
                   expand = c(0.15, 0.05)) +
  theme_void(base_size = 12) +
  guides(fill = guide_legend(title = "DKS score"))
Figure4A
```
<!--  BVD-523 has no target and but our pipeline predicts that it as CINP -->
```{r}
DOI='BVD-523'; BestPredicted_Target='CINP'
# sum(expression_matched[CurrWrong_Target,]<3)
DOI_id=KnownTarget_predictions$drugBroadID[grep(DOI, KnownTarget_predictions$drugName)]
Figure4B_data=rbind(data.frame(Target='Predicted Target',
                               TargetName=BestPredicted_Target,
                               CRISPR_KO=avana_matched[BestPredicted_Target,],
                               drug_response=drug_matched[DOI_id,],
                               drugName=DOI
                               )
                    )
# Figure4B <- ggplot(Figure4B_data, aes(x=CRISPR_KO, y=drug_response))+
#   geom_point()+
#   stat_smooth(method = 'lm', se = T)+
#   facet_wrap(.~Target+TargetName, scales = 'free')+
#   theme_bw(base_size = 12)+
#   labs(x='Viability after CRISPR-KO',
#        y=paste('Response to', DOI))+
#   stat_cor(size=4)+
#   theme(legend.position = 'top')
# Figure4B
```
<!--  Pibenzimol has no target and but our pipeline predicts that it as UBE2Q1 -->
```{r}
DOI='Pibenzimol'; BestPredicted_Target='UBE2Q1'
DOI_id=KnownTarget_predictions$drugBroadID[grep(DOI, KnownTarget_predictions$drugName, ignore.case = T)]
Figure4C_data=rbind(data.frame(Target='Predicted Target',
                               TargetName=BestPredicted_Target,
                               CRISPR_KO=avana_matched[BestPredicted_Target,],
                               drug_response=drug_matched[DOI_id,],
                               drugName=DOI
                               )
                    )
# Figure4C <- ggplot(Figure4C_data, aes(x=CRISPR_KO, y=drug_response))+
#   geom_point()+
#   stat_smooth(method = 'lm', se = T)+
#   facet_wrap(.~Target+TargetName, scales = 'free')+
#   theme_bw(base_size = 12)+
#   labs(x='Viability after CRISPR-KO',
#        y=paste('Response to', DOI))+
#   stat_cor(size=4)+
#   theme(legend.position = 'top')
# Figure4C
```
<!--  Iobenguane has no target and but our pipeline predicts that it as BestPredicted_Target -->
```{r}
DOI='Iobenguane';
DOI_id=KnownTarget_predictions$drugBroadID[grep(DOI, KnownTarget_predictions$drugName, ignore.case = T)]
BestPredicted_Target=KnownTarget_predictions$BestTargetName[grep(DOI, KnownTarget_predictions$drugName, ignore.case = T)]
Figure4D_data=rbind(data.frame(Target='Predicted Target',
                               TargetName=BestPredicted_Target,
                               CRISPR_KO=avana_matched[BestPredicted_Target,],
                               drug_response=drug_matched[DOI_id,],
                               drugName=DOI
                               )
                    )
# Figure4D <- ggplot(Figure4D_data, aes(x=CRISPR_KO, y=drug_response))+
#   geom_point()+
#   stat_smooth(method = 'lm', se = T)+
#   facet_wrap(.~Target+TargetName, scales = 'free')+
#   theme_bw(base_size = 12)+
#   labs(x='Viability after CRISPR-KO',
#        y=paste('Response to', DOI))+
#   stat_cor(size=4)+
#   theme(legend.position = 'top')
# Figure4D
```
<!--  Temoporfin has no target and but our pipeline predicts that it as BestPredicted_Target -->
```{r}
DOI='temoporfin';
DOI_id=KnownTarget_predictions$drugBroadID[grep(DOI, KnownTarget_predictions$drugName, ignore.case = T)]
BestPredicted_Target=KnownTarget_predictions$BestTargetName[grep(DOI, KnownTarget_predictions$drugName, ignore.case = T)]
Figure4E_data=rbind(data.frame(Target='Predicted Target',
                               TargetName=BestPredicted_Target,
                               CRISPR_KO=avana_matched[BestPredicted_Target,],
                               drug_response=drug_matched[DOI_id,],
                               drugName=DOI
                               )
                    )
```

```{r}
Figure4B2D_data=rbind(Figure4B_data, Figure4C_data, Figure4D_data, Figure4E_data)
Figure4B2D <- ggplot(Figure4B2D_data, aes(x=CRISPR_KO, y=drug_response))+
  geom_point()+
  stat_smooth(method = 'lm', se = T)+
  facet_wrap(drugName~Target+TargetName, scales = 'free')+
  theme_bw(base_size = 12)+
  labs(x='Viability after CRISPR-KO',
       y=paste('Drug response'))+
  stat_cor(size=4)+
  theme(legend.position = 'top')
```

```{r}
Figure4 <- grid.arrange(Figure4A,Figure4B2D, layout_matrix=rbind(c(1, 2)))
ggsave(Figure4, filename = '/Users/sinhas8/Project_TrueTarget/Results/Figure4v0.png',
       width = 9, height = 5)
ggsave(Figure4, filename = '/Users/sinhas8/Project_TrueTarget/Results/Figure4v0.pdf',
       width = 9, height = 5)
```


