---
title: "Figure 2 Mutation Data"
output: html_notebook
---
## Complete Figure 2: Identifying whether the drug bind more specifically to the mutant or wild-type form of a drug.

<!-- Figure 2: Identifying whether the drug bind more specifically to the mutant or wild-type form of a drug. -->
```{r}
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
```

<!-- Figure 2A - Viability of BRAF after CRISPR KO:  Proof of concept of our pipeline’s ability to predict mutation-specific targeting for Dabrafenib -->
```{r}
# mut_diffential_targeting_drugs[grep('BRAF',mut_diffential_targeting_drugs$MaxTargetName),]
GOI = 'BRAF';DOI = 'Dabrafenib'
DOI_id = mut_diffential_targeting_drugs$drugBroadID[match_stripall( DOI, mut_diffential_targeting_drugs$drugName)]
Figure_2A_data = data.frame(crispr = avana_matched['BRAF',], Dabrafenib = drug_matched[DOI_id,], BRAF_mutation = mutation_matched['BRAF',])
Figure_2A_data$BRAF_mutation = factor(Figure_2A_data$BRAF_mutation)
levels(Figure_2A_data$BRAF_mutation) = c('WT', 'V600E')
Figure_2A <- ggplot(Figure_2A_data, aes(x = crispr, y = Dabrafenib, color = factor(BRAF_mutation)))+
  # geom_point()+
  stat_smooth(method = 'lm')+
  theme_bw(base_size = 15)+
  labs(x = 'Viability after BRAF CRISPR-KO', y = 'Response to Dabrafenib', color = 'BRAF\nmutation\nstatus')+
  stat_cor(label.y = c(1.3,1.4))
Figure_2A
```


<!-- Figure 2B - Landscape of all differential binding -->
```{r}
Figure_2B_data = KnownTarget_predictions
Figure_2B_data$ann = ''
Figure_2B_data$ann = paste(Figure_2B_data$drugName, Figure_2B_data$MaxTargetName,sep = ';')
Figure_2B_data[grep('BRAF',Figure_2B_data$MaxTargetName),]


Figure_2B <- ggplot(Figure_2B_data, aes(y =  mutation_interaction_strength,
                                     x = -log10(mutation_interaction_P),
                                     color = mutation_interaction_P<0.05,
                                     label = ann))+
  geom_point()+
  theme_bw(base_size = 15)+
  theme(legend.position = 'none')+
  geom_label_repel(data = subset(Figure_2B_data,
                                 Figure_2B_data$mutation_interaction_P<0.01))+
  geom_vline(xintercept = 1.3, linetype = 'dashed',color = 'blue')+
  labs(x = '-log10(Significance)', y = 'Differential targeting to\nmutant vs WT')
Figure_2B
```

## ADD the Figure 2C-H from Step_7 mutation dependency file after sanju correct it.
<!-- Figure 2C : data distribution of negative control and resistance mutation -->
```{r}

```

<!--Figure 2D -->
```{r}

```

<!--Figure 2E -->
```{r}

```
<!--Figure 2F -->
```{r}

```
<!--Figure 2G -->
```{r}

```
<!--Figure 2H -->
```{r}

```

<!-- Landscape of differential targeting drugs -->
<!-- Correlation between BRAF inhibitor phase and BRAF V600E specificity -->
```{r}
#Mutation interaction corr with clinical advancement
KnownTarget_predictions$Stage = factor(KnownTarget_predictions$phase)
levels(KnownTarget_predictions$Stage) = c(4,1,2, 2, 3, 3, 0, -1)
# cor.test(factor2numeric(KnownTarget_predictions$Stage)[braf_id],
#          KnownTarget_predictions$mutation_interaction_strength[braf_id])

mut_diffential_targeting_drugs = KnownTarget_predictions[which(KnownTarget_predictions$mutation_interaction_P<0.05),]
#Mutation interaction corr with target corr
braf_id = grep('BRAF',KnownTarget_predictions$MaxTargetName)
df2plot_Data_figure_2I = KnownTarget_predictions[braf_id,]
```

<!-- Plot 2I: The extent of mutation-specific targeting (V600E) for various clinical phases of BRAF inhibitors -->
```{r}
df2plot_Data_figure_2I$phase = factor(df2plot_Data_figure_2I$phase)
levels(df2plot_Data_figure_2I$phase)[2] = 'Phase1-2'
Figure_2I <- ggplot(df2plot_Data_figure_2I, aes(x = reorder(phase, mutation_interaction_strength), y = mutation_interaction_strength))+
  geom_boxplot()+
  theme_bw(base_size = 15)+
  labs(x = 'Clinical Phases', y = 'Extent of differential targeting\nof V600E')+
  stat_compare_means(comparisons = combn(levels(df2plot_Data_figure_2I$phase), 2, simplify = F))+
  theme(axis.text.x = element_text(size=10, angle = -20, vjust = -0.4))
Figure_2I
```

<!-- Find genes that are most frequenty targeted by differential targeting drugs -->
```{r}
more2mutant = which(mut_diffential_targeting_drugs$mutation_interaction_strength>0)
not_low_expresed = which(mut_diffential_targeting_drugs$KnownTarget_meanCorr>3)
more2WT = which(mut_diffential_targeting_drugs$mutation_interaction_strength<0)
```

<!-- Plot 2J: Response to Olaparib  vs. viability after PARP1 KO cell lines with (PARP mutation vs WT) -->
```{r}
mut_diffential_targeting_drugs_approved = mut_diffential_targeting_drugs[which(mut_diffential_targeting_drugs$phase=='Launched'),]
mut_diffential_targeting_drugs_approved[
  order(mut_diffential_targeting_drugs_approved$mutation_interaction_strength*
          (-log10(mut_diffential_targeting_drugs_approved$mutation_interaction_P))),]

GOI = 'PARP1';DOI = 'olaparib'
DOI_id = mut_diffential_targeting_drugs$drugBroadID[match_stripall( DOI, mut_diffential_targeting_drugs$drugName)]
Figure_2J_data = data.frame(crispr = avana_matched[GOI,], drug_response = drug_matched[DOI_id,], mutation = mutation_matched[GOI,])
Figure_2J_data$mutation = factor(Figure_2J_data$mutation)
levels(Figure_2J_data$mutation) = c('WT', 'mutant')
Figure_2J <- ggplot(Figure_2J_data, aes(x = crispr, y = drug_response, color = factor(mutation)))+
  stat_smooth(method = 'lm', se=F)+
  theme_bw(base_size = 15)+
  labs(x = 'Viability after PARP CRISPR-KO', y = 'Response to Olaparib', color = 'PARP1\nmutation\nstatus')+
  stat_cor(label.y = c(1.2,1.3), size = 3)
Figure_2J
```
<!-- Plot 2K: Response to oxibendazole vs. viability after TUBB KO cell lines similar as above -->
```{r}
mut_diffential_targeting_drugs_approved = mut_diffential_targeting_drugs[which(mut_diffential_targeting_drugs$phase=='Launched'),]
mut_diffential_targeting_drugs_approved[
  order(mut_diffential_targeting_drugs_approved$mutation_interaction_strength*
          (-log10(mut_diffential_targeting_drugs_approved$mutation_interaction_P))),]

mut_diffential_targeting_drugs[grep('TUBA1B',mut_diffential_targeting_drugs$MaxTargetName),]
GOI = 'TUBA1B';DOI = 'vinorelbine'
DOI_id = mut_diffential_targeting_drugs$drugBroadID[match_stripall( DOI, mut_diffential_targeting_drugs$drugName)]
Figure_2K_data = data.frame(crispr = avana_matched[GOI,], drug_response = drug_matched[DOI_id,], mutation = mutation_matched[GOI,])
Figure_2K_data$mutation = factor(Figure_2K_data$mutation)
levels(Figure_2K_data$mutation) = c('WT', 'mutant')
Figure_2K <- ggplot(Figure_2K_data, aes(x = crispr, y = drug_response, color = factor(mutation)))+
  stat_smooth(method  =  'lm', se = F)+
  theme_bw(base_size = 12)+
  labs(x = 'Viability after TUBB CRISPR-KO', y = 'Response to oxibendazole', color = 'TUBB\nmutation\nstatus')+
  stat_cor(label.y = c(0.8,0.9), size = 3)
Figure_2K
```
<!-- Adding all figures together -->
```{r}
# Figure_2 <- grid.arrange(Figure_2A,Figure_2B,
#                          Figure_2C,Figure_2D,
#                          Figure_2E,Figure_2F,
#                          Figure_2G,Figure_2H,
#                          Figure_2I,Figure_2J,Figure_2K)
# 
# ggsave(Figure4, filename = '../result/Figure2v0.pdf',
#        width = 9, height = 5)
```


