---
title: "Figure 3 and supplementary figure 12"
output: html_notebook
---

## Note
<!--question1: supplmentary figure 11 ask sanju
question 2: AUC plot
question 3: R and p values are changing slightly ask sanju-->
## Note

<!-- Figure 3 Section: Chart the landscape of secondary Targets. Identifying secondary targets of drugs that mediate the response when the primary target is not expressed.  -->
<!-- Chart the landscape of secondary Targets -->
<!-- required library and steps-->
<!-- Step 1: identify secondary known targets of each drug -->
```{r}
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
```

<!-- # Df required -->
```{r}
## correlation matrix between the drug response and the crispr KO for secondary target is required here
drugVScrispr_corr_features_list_secondary = readRDS('../Data/drugVScrispr_corr_features_list_secondary.RDS')
sec_corrMat=do.call(cbind, sapply(drugVScrispr_corr_features_list_secondary, function(x) err_handle(x[,2])))
sec_corrMat_P=do.call(cbind, sapply(drugVScrispr_corr_features_list_secondary, function(x) err_handle(x[,1])))
sec_corrMat_rank=apply(-sec_corrMat, 2, rank)
```

<!-- Figure 3A:  Viability after BTK KO vs. Ibrutinib response and it's predicted secondary target 'EGFR'-->
```{r}
Primary_Target='BTK'; DOI='Ibrutinib'; sec_Target='EGFR'
DOI_id=KnownTarget_predictions$drugBroadID[match_stripall(DOI, KnownTarget_predictions$drugName)]
Figure3A_data=rbind(data.frame(Target='Primary Target',
                               TargetName='BTK',
                               CRISPR_KO=avana_matched[Primary_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<2, labels = c('High', 'Low'))),
                    data.frame(Target='Secondary Target',
                               TargetName='EGFR',
                               CRISPR_KO=avana_matched[sec_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<0.05, labels = c('High', 'Low'))))

Figure3A <- ggplot(Figure3A_data, aes(x=CRISPR_KO, y=drug_response, color=expression))+
  # geom_point()+
  stat_smooth(method = 'lm', se = T)+
  facet_wrap(.~Target+TargetName, scales = 'free')+
  theme_bw(base_size = 12)+
  labs(x='Viability after CRISPR-KO',
       y='Response to Ibrutinib',
       color='BTK\nexpression\nstatus')+
  stat_cor(label.y = c(1.2,1.4), size=4)+
  theme(legend.position = 'top')
Figure3A
```

<!-- Figure 3B: The strength of correlation of ibrutinib response and viability after KO of each gene -->
```{r}
## corrMat is defined as correlation strength, P value and the rank of the correlation matrix between the drug response and the crispr KO.
## corrMat, corrMat_rank, corrMat_P variables are from step 0B.
Figure3B_data=data.frame(Ibrutinib_Rho=corrMat[,DOI_id],
                         Ibrutinib_Rho_rank=corrMat_rank[,DOI_id],
                         Ibrutinib_Rho_P=corrMat_P[,DOI_id])
Figure3B_data$ann=''
Figure3B_data$ann[Figure3B_data$Ibrutinib_Rho>0.28]=rownames(corrMat_P)[Figure3B_data$Ibrutinib_Rho>0.28]
  
Figure3B <- ggplot(Figure3B_data, aes(y=Ibrutinib_Rho,
                                      color=Ibrutinib_Rho_rank,
                                      x= -log10(Ibrutinib_Rho_P), 
                                      label=ann))+
  geom_point()+
  # stat_smooth(method = 'lm', se = T)+
  theme_bw(base_size = 12)+
  labs(y='Correlation between gene\nKO and Ibrutinib response\nin no-BTK cell lines',
       x='-log10(P)',
       color='Rank')+
  geom_label_repel(nudge_y = c(-0.1, -0.2))+
  theme(legend.position = 'top', legend.text = element_text(size=8))
Figure3B
```

<!-- Only focus on drugs where the primary target is correct -->
```{r}
correctly_predicted=which(KnownTarget_predictions$PredictedRank<523)
```

```{r}
count_correct_direction_prop=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]<0, na.rm = T)/
  length(na.omit(KnownTarget_predictions$interaction_strength[correctly_predicted]))

count_sig_correct_direction=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]<0 &
      KnownTarget_predictions$mutation_interaction_P[correctly_predicted]<0.05, na.rm = T)
count_sig_wrong_direction=sum(KnownTarget_predictions$interaction_strength[correctly_predicted]>0 &
      KnownTarget_predictions$mutation_interaction_P[correctly_predicted]<0.05, na.rm = T)
count_sig_correct_direction/(count_sig_correct_direction+count_sig_wrong_direction)
```

```{r}
correctly_pred_KnownTarget_predictions=KnownTarget_predictions[correctly_predicted,]
Figrue3C_data=correctly_pred_KnownTarget_predictions
Figrue3C_data$direction='+ve Interaction'
Figrue3C_data$direction[Figrue3C_data$interaction_strength<0]='-ve Interaction'
Figrue3C_data$direction[Figrue3C_data$interaction_strength<0 & 
                                  Figrue3C_data$interaction_P<0.1 ]='Sig -ve\nInteraction'

sum(Figrue3C_data$interaction_strength<0, na.rm=T)/length(na.omit(Figrue3C_data$interaction_strength))
Figrue3C <- ggplot(Figrue3C_data, aes(y=interaction_strength,
                          x= -log10(mutation_interaction_P),
                                    color=direction
                                    ))+
  geom_point()+
  theme_bw(base_size = 15)+
  labs(x='-log10(P)', y='Dependency of correlation\non expression', )+
  theme(legend.position = 'top',legend.title = element_blank())+
  guides(color=guide_legend(nrow=3,byrow=TRUE))
Figrue3C
```

<!-- Test the power of our secondary target prediction -->
<!-- Validate secondary targets -->
```{r}
KnownTarget_predictions$allKnownTargets=
  onTarget$drugCategory$target[match(KnownTarget_predictions$drugBroadID, onTarget$drugCategory$broad_id_trimmed)]
allKnownTargets_list=strsplit(as.character(KnownTarget_predictions$allKnownTargets), split = ', ')

Sec_KnownTargets_list=sapply(1:nrow(KnownTarget_predictions), function(x){
  primary_target_id=grep(KnownTarget_predictions$MaxTargetName[x], allKnownTargets_list[[x]])
  allKnownTargets_list[[x]][-primary_target_id]
})
names(Sec_KnownTargets_list)=KnownTarget_predictions$drugBroadID
```
<!-- identify the drugs where the primary target is correct -->
```{r}
correctly_predict_drugID=KnownTarget_predictions$drugBroadID[which(KnownTarget_predictions$PredictedRank<523)]

#Get the best ranking of secondary target for each of these drugs
Sec_KnonwTarget_score_step1vs3=sapply(correctly_predict_drugID, function(x)

  err_handle(data.frame(drugName=x,
           secKnownTarget_Step1=Sec_KnownTargets_list[[x]][which.max(corrMat_rank[Sec_KnownTargets_list[[x]], x])],
           secKnownTarget_Step3=Sec_KnownTargets_list[[x]][which.max(sec_corrMat_rank[Sec_KnownTargets_list[[x]], x])],
           SecKnown_Pred_rank_Step1=min(corrMat_rank[Sec_KnownTargets_list[[x]], x], na.rm = T) ,
           SecKnown_Pred_rank_Step3=min(sec_corrMat_rank[Sec_KnownTargets_list[[x]], x], na.rm = T) 
           ))
)
Sec_KnonwTarget_score_step1vs3_df=do.call(rbind, Sec_KnonwTarget_score_step1vs3)
Sec_KnonwTarget_score_step1vs3_df
Sec_KnonwTarget_score_step1vs3_df_long = tidyr::gather(Sec_KnonwTarget_score_step1vs3_df, Step, Corr_strength_rank, SecKnown_Pred_rank_Step1:SecKnown_Pred_rank_Step3, factor_key=TRUE)
Sec_KnonwTarget_score_step1vs3_df_long=Sec_KnonwTarget_score_step1vs3_df_long[-grep('TP53',Sec_KnonwTarget_score_step1vs3_df_long$secKnownTarget_Step1),]
```
<!-- Comapre the prediction rank from step 1 vs step 3, Confounding by mean random  rank. -->
```{r}
# Sec_KnonwTarget_score_step1vs3_df_long$Step=factor(Sec_KnonwTarget_score_step1vs3_df_long$Step)
# levels(Sec_KnonwTarget_score_step1vs3_df_long$Step)=c('Correlation based on\n all cell lines',
#                                                       'Correlation based on\ncell lines with\nno-expression of primary\ntarget')
```

```{r}
# ggpaired(Sec_KnonwTarget_score_step1vs3_df_long, y='Corr_strength_rank', x='Step',
#  color = 'Step', line.color = "gray", line.size = 0.4,
#  palette = "npg", )
```
```{r}
# FigureS8 <-  ggplot(Sec_KnonwTarget_score_step1vs3_df, aes(y=SecKnown_Pred_rank_Step1, x=SecKnown_Pred_rank_Step3))+
#   geom_point()+
#   geom_abline(intercept = 0, slope = 1, linetype='dashed', color='blue')+
#   theme_bw(base_size = 13)+
#   labs(y='Correlation based on\n all cell lines',x='Correlation based on cell lines with\nno-expression of primary target')
```
<!-- Identify drugs who secondary target can only be identified using second step -->
```{r}
secTarget_correctly_predicted=Sec_KnonwTarget_score_step1vs3_df$drugName[which(Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step3<523 &
                                                                         Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step1>523)
                                                                         ]
```
<!--Validation of secondary target-->
<!-- Create random negative labels & their score. Next, get score of positive labels from Step 1 vs 3. -->
<!-- We create random labels for each drug & get their score -->
```{r}
#Get the best ranking of secondary target for each of these drugs
step1_vs_step3<- function(seed_id=1, rank_threshold=2){
  correctly_predict_drugID=KnownTarget_predictions$drugBroadID[which(KnownTarget_predictions$PredictedRank<rank_threshold)]
  set.seed(seed_id)
  negative_labels=sample(1:nrow(corrMat_rank), size = length(correctly_predict_drugID))
  #respective drugs for which this negative label is provided
  names(negative_labels)=correctly_predict_drugID
  
  Sec_KnonwTarget_score_step1vs3=sapply(correctly_predict_drugID, function(x)
    
    err_handle(data.frame(drugName=x,
                          secKnownTarget_Step1=Sec_KnownTargets_list[[x]][which.max(corrMat_rank[Sec_KnownTargets_list[[x]], x])],
                          secKnownTarget_Step3=Sec_KnownTargets_list[[x]][which.max(sec_corrMat_rank[Sec_KnownTargets_list[[x]], x])],
                          SecKnown_Pred_rank_Step1=min(corrMat_rank[Sec_KnownTargets_list[[x]], x], na.rm = T) ,
                          Control_Step1=corrMat_rank[negative_labels[x], x],
                          SecKnown_Pred_rank_Step3=min(sec_corrMat_rank[Sec_KnownTargets_list[[x]], x], na.rm = T),
                          Control_Step3=sec_corrMat_rank[negative_labels[x], x],
                          Control=rownames(corrMat_rank)[negative_labels[x]]
    ))
  )
  Sec_KnonwTarget_score_step1vs3_df=do.call(rbind, Sec_KnonwTarget_score_step1vs3)
  Sec_KnonwTarget_score_step1vs3_df=na.omit(Sec_KnonwTarget_score_step1vs3_df)
  Sec_KnonwTarget_score_step1vs3_df=Sec_KnonwTarget_score_step1vs3_df[-grep('TP53',Sec_KnonwTarget_score_step1vs3_df$secKnownTarget_Step1),]
  Score_from_Step1=rbind(data.frame(label='Positive', Score=Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step1),
                         data.frame(label='Negative', Score=Sec_KnonwTarget_score_step1vs3_df$Control_Step1))
  Score_from_Step3=rbind(data.frame(label='Positive', Score=Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step3),
                         data.frame(label='Negative', Score=Sec_KnonwTarget_score_step1vs3_df$Control_Step3))
  Score_from_Step13_combination=rbind(data.frame(label='Positive',
                                                 Score=pmin(Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step1,
                                                           Sec_KnonwTarget_score_step1vs3_df$SecKnown_Pred_rank_Step3)),
                                      data.frame(label='Negative', 
                                                 Score=Sec_KnonwTarget_score_step1vs3_df$Control_Step3))
  power_step1=roc(Score_from_Step1$label, Score_from_Step1$Score)
  power_step3=roc(Score_from_Step3$label, Score_from_Step3$Score)
  power_step13_comb=roc(Score_from_Step13_combination$label, Score_from_Step13_combination$Score)
  
  list(Score_from_Step1=Score_from_Step1, 
       Score_from_Step3=Score_from_Step3,
       Score_from_Step13_combination=Score_from_Step13_combination,
       step1_roc= power_step1,
       step3_roc=power_step3, 
       step12_comb_roc=power_step13_comb)
}

```

```{r}
power_s1vsS3=lapply(1:10, function(x) step1_vs_step3(seed_id = x, rank_threshold = 2))
## to check which seed hacve best auc
AUC_across_all_seeds= sapply(power_s1vsS3, function(y) sapply(y[4:6], function(x) x$auc))
```
<!-- box plot Figure 3D -->
```{r}
## best AUC is reached when we set the seed to 1
S1vsS3_seed1 = power_s1vsS3[[1]]

Score_from_Step3=S1vsS3_seed1$Score_from_Step3
Figure3D <- ggplot(Score_from_Step3, aes(y=Score, x=label))+
  geom_boxplot()+
  stat_compare_means(label = 'p')+
  theme_bw(base_size = 15)+
  labs(y='Predicted Rank from Step3', x='Ground Truth Labels')
Figure3D
```
<!-- Figure 3E -->
```{r}
Score_from_Step1=S1vsS3_seed1$Score_from_Step1
Figure3E <- ggplot(Score_from_Step1, aes(y=Score, x=label))+
  geom_boxplot()+
  stat_compare_means(label = 'p')+
  theme_bw(base_size = 15)+
  labs(y='Predicted Rank Step1', x='Ground Truth Labels')
Figure3E
```
<!-- Figure 3F -->
```{r}
Score_from_Step13_combination=S1vsS3_seed1$Score_from_Step13_combination
Figure3F <- ggplot(Score_from_Step13_combination, aes(y=Score, x=label))+
  geom_boxplot()+
  stat_compare_means(label = 'p')+
  theme_bw(base_size = 15)+
  labs(y='Predicted Rank Step1+3', x='Ground Truth Labels')
Figure3F
```
<!-- Plot all AUC together -->
```{r}
secTargetROC_list=lapply(S1vsS3_seed1[4:6], smooth)
# Add mean AUC
names(secTargetROC_list)=c(paste('Step1 =', round(secTargetROC_list$step1_roc$auc[1],2)),
                           paste('Step3 =', round(secTargetROC_list$step3_roc$auc[1],2)),
                           paste('Step1+3 =', round(secTargetROC_list$step12_comb_roc$auc[1],2)))


Figure3G <- ggroc(secTargetROC_list)+ 
  theme_bw(base_size = 11) + 
  theme(legend.title = element_blank(), 
        legend.position = c(0.7, 0.25),
        legend.text = element_text(size=12),
        text = element_text(size=11)) +
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="grey", linetype="dashed")+
  labs(title="", x="Specificity", y="Sensitivity")
Figure3G
```

<!-- CDK6 vs CDK4 -->
```{r}
Primary_Target='CDK6'; DOI='palbociclib'; sec_Target='CDK4'
sum(expression_matched[Primary_Target,]<3)
DOI_id=KnownTarget_predictions$drugBroadID[match_stripall(DOI, KnownTarget_predictions$drugName)]
Figure6B_data=rbind(data.frame(Target='Primary Target',
                               TargetName=Primary_Target,
                               CRISPR_KO=avana_matched[Primary_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<3, labels = c('High', 'Low'))),
                    data.frame(Target='Secondary Target',
                               TargetName=sec_Target,
                               CRISPR_KO=avana_matched[sec_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<3, labels = c('High', 'Low'))))

Figure3H <- ggplot(Figure6B_data, aes(x=CRISPR_KO, y=drug_response, color=expression))+
  # geom_point()+
  stat_smooth(method = 'lm', se = T)+
  facet_wrap(.~Target+TargetName, scales = 'free')+
  theme_bw(base_size = 12)+
  labs(x='Viability after CRISPR-KO',
       y='Response to palbociclib',
       color='CDK6 expression\nstatus')+
  stat_cor(label.y = c(0.93,0.96), size=4)+
  theme(legend.position = 'top')
Figure3H
```
<!-- Saving Figure 3 -->
```{r, fig.width=5, fig.height=4}
Figure3 <-grid.arrange(Figure3A, Figure3B, Figrue3C,
                       Figure3D, Figure3E, Figure3F,Figure3G,
                       Figure3H,
                       layout_matrix = rbind(c(1, 1, 2, 3), c(4, 5, 6, 7), c(8,8,NA, NA)) 
                       )

ggsave(Figure3, filename = '../result/Figure3v1.pdf',
       width = 10, height = 12)
```

<!-- Supplementary figure 12: The response to Tamibarotene vs viability after CRISPR KO of RARA and RARB in cell lines with RARA high vs low expression cell lines -->
<!-- RARA vs RARB -->
```{r}
Primary_Target='RARA'; DOI='tamibarotene'; sec_Target='RARB'
# sum(expression_matched[Primary_Target,]<3)
DOI_id=KnownTarget_predictions$drugBroadID[match_stripall(DOI, KnownTarget_predictions$drugName)]
FigureS9_data=rbind(data.frame(Target='Primary Target',
                               TargetName=Primary_Target,
                               CRISPR_KO=avana_matched[Primary_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<3, labels = c('High', 'Low'))),
                    data.frame(Target='Secondary Target',
                               TargetName=sec_Target,
                               CRISPR_KO=avana_matched[sec_Target,],
                               drug_response=drug_matched[DOI_id,],
                               expression=factor(expression_matched[Primary_Target,]<3, labels = c('High', 'Low'))))

Figure_supp_12 <- ggplot(FigureS9_data, aes(x=CRISPR_KO, y=drug_response, color=expression))+
  # geom_point()+
  stat_smooth(method = 'lm', se = T)+
  facet_wrap(.~Target+TargetName, scales = 'free')+
  theme_bw(base_size = 12)+
  labs(x='Viability after CRISPR-KO',
       y='Response to tamibarotene',
       color='RARA expression\nstatus')+
  stat_cor(label.y = c(0.93,0.96), size=4)+
  theme(legend.position = 'top')
Figure_supp_12 

ggsave(Figure_supp_12, filename = '../result/FigureS9v0.pdf',
       width = 6, height = 4)
```
