---
title: "R Notebook"
output: html_notebook
---
 
<!-- Finding drugs that may target Undruggable oncogenes -->
<!-- Find best target of each drug -->
```{r}
Predicted_Target=apply(drugVScrispr_corr_Strength, 2, function(x) c(target=all_genenames[which.max(x)],
                                                                    cor=as.numeric(x[which.max(x)]) ) )
Predicted_Target=as.data.frame(t(Predicted_Target))
Predicted_Target$cor=as.numeric(Predicted_Target$cor)
# Predicted_Best_Drug=apply(drugVScrispr_corr_Strength, 1,function(x) c(drug=all_drugNames[which.max(x)],
#                                                                       cor=as.numeric(x[which.max(x)]) ) )
# Predicted_Best_Drug=t(Predicted_Best_Drug)
Predicted_Target
```
<!-- Undruggable oncogenes -->
```{r}
undruggable=c('KRAS', 'MYC', 'AR', 'NOTCH1', 'BRD', 'BCL2')
Predicted_Target[!is.na(match(Predicted_Target$target, undruggable)),]
sapply(undruggable, function(x) Predicted_Target$target[grep(x,Predicted_Target$target)])
```
