---
title: "R Notebook"
output: html_notebook
---

<!-- Compute which drugs whose target KO and drug response viability similarity dimnishes when target expression is not expressed -->
<!-- Function and libraries used -->
```{r}
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
```
<!-- Add BTK as target manually -->
```{r}
KnownTarget_predictions[grep('ibru',KnownTarget_predictions$drugName),]
KnownTarget_predictions$MaxTargetName[grep('ibru',KnownTarget_predictions$drugName)][1]='BTK'
```
<!-- MATCHED MATRIX -->
```{r}
matched_cellLines = Reduce(intersect, 
                         list(colnames(onTarget$expression),
                              colnames(onTarget$avana_22Q2),
                              colnames(onTarget$secondary_prism),
                              colnames(onTarget$mutations_matrix)
                              ))
expression_matched = onTarget$expression[,matched_cellLines]
avana_matched = onTarget$avana_22Q2[,matched_cellLines]
drug_matched = onTarget$secondary_prism[,matched_cellLines]

dim(onTarget$mutations_matrix)
```

<!-- Compute cell lines with low vs high expression -->
<!-- Only for drugs with targets with non-zero low expression cell lines can be used in interaction analysis -->
<!-- Most of the drug targets are never zero expressed -->
```{r}
cellLines_with_LowTarget = sapply(KnownTarget_predictions$MaxTargetName,
                                function(x) 
                                  err_handle(sum(expression_matched[x,]<2)) )
hist(cellLines_with_LowTarget)
KnownTarget_predictions$cellLines_withLOWexp = cellLines_with_LowTarget
```

```{r}
wilcox.test(KnownTarget_predictions$cellLines_withLOWexp,
            xtile(KnownTarget_predictions$Maxcorr, 2), alternative = 'g')
KnownTarget_predictions$Maxcorr_Q=xtile(KnownTarget_predictions$Maxcorr, 2)
ggplot(na.omit(KnownTarget_predictions), aes(y=cellLines_withLOWexp,
                                    x=factor(Maxcorr_Q)))+
  geom_boxplot()+
  stat_compare_means()+
  theme_bw(base_size = 20)
```
<!-- Targets with low expression in at least five cell lines -->
```{r}
Targets_wd_lowExp_atLeast_FiveCellLines=KnownTarget_predictions$cellLines_withLOWexp>5
```
<!-- Compute interaction -->
<!-- Preprocessing -->
```{r}
KnownTarget_predictions$drugBroadID=onTarget$drugCategory$broad_id_trimmed[match(KnownTarget_predictions$drugName, onTarget$drugCategory$name)]
# Compute interaction in all cases
interaction_Features=lapply(1:nrow(KnownTarget_predictions), function(x)
  {
  infunc_drug_matched=err_handle(drug_matched[KnownTarget_predictions$drugBroadID[x],])
  infunc_avana_matched=err_handle(avana_matched[KnownTarget_predictions$MaxTargetName[x],])
  infunc_expression_matched=err_handle(expression_matched[KnownTarget_predictions$MaxTargetName[x],]<2)
  err_handle(summary(lm(infunc_drug_matched ~ 
                infunc_avana_matched*infunc_expression_matched))$coefficients[4,c(1,4)])
  }
  )
names(interaction_Features)=KnownTarget_predictions$drugName
# This is an interaction where the where cell lines with low expression (<2, Trues in above vector) will have "lower" correlation strength than cell lines with high expression (>2, Falses in above vector)
KnownTarget_predictions$Whether_interaction=sapply(interaction_Features, function(x) x[1]<0 & x[2]<0.2 )
KnownTarget_predictions$interaction_strength=sapply(interaction_Features, function(x) x[1])
KnownTarget_predictions$interaction_P=sapply(interaction_Features, function(x) x[2])
```
<!-- Test case -->
```{r}
# x=1
# infunc_drug_matched=err_handle(drug_matched[KnownTarget_predictions$drugBroadID[x],])
# infunc_avana_matched=err_handle(avana_matched[KnownTarget_predictions$MaxTargetName[x],])
# infunc_expression_matched=err_handle(expression_matched[KnownTarget_predictions$MaxTargetName[x],]<1)
# lm_model=lm(infunc_drug_matched ~ 
#                 infunc_avana_matched*infunc_expression_matched)
# err_handle(summary(lm_model)$coefficients[4,c(1,4)])
# interact_plot(lm_model, pred = infunc_avana_matched, modx = infunc_expression_matched)
```
<!-- Drug targets that show interaction are predicted to be more likely to be the true target from our pipeline -->
```{r}
ggplot(na.omit(KnownTarget_predictions),
       aes(x=Whether_interaction, y=Maxcorr))+
  geom_boxplot()+
  stat_compare_means()+
  theme_bw(base_size = 20)
```
<!-- Which Drugs have interactions - -->
<!-- Preprocessing -->
```{r}
table(KnownTarget_predictions$Whether_interaction)
head(drugVScrispr_corr_Strength[,1])
drugVScrispr_corr_Strength_ranked=apply(drugVScrispr_corr_Strength, 2, function(x) nrow(drugVScrispr_corr_Strength)-rank(x)+1 )
myhead(drugVScrispr_corr_Strength_ranked)
# KTP stands for "KnownTarget_predictions" matrix
map_KTP_rankedMat=match(KnownTarget_predictions$drugBroadID, colnames(drugVScrispr_corr_Strength_ranked))

drug_targets_ordered=KnownTarget_predictions$MaxTargetName[map_KTP_rankedMat]
KnownTarget_predictions$PredictedRank=sapply(1:length(map_KTP_rankedMat), function(x) 
  err_handle(drugVScrispr_corr_Strength_ranked[KnownTarget_predictions$MaxTargetName[x],
                                               map_KTP_rankedMat[x] ])  )
```
<!-- Their features  -->
```{r}
KnownTarget_predictions$PredictedRank
ggplot(na.omit(KnownTarget_predictions),
       aes(x=Whether_interaction, y=PredictedRank))+
  geom_boxplot()+
  stat_compare_means()+
  theme_bw(base_size = 20)
```
<!-- drugs where predicted target is known target and interation is present -->
```{r}
drugs_wdBoth_interaction_andTrueKnownTarget=KnownTarget_predictions$PredictedRank < 100 & KnownTarget_predictions$Whether_interaction
drugCandidates_for_secTargets=KnownTarget_predictions[which(drugs_wdBoth_interaction_andTrueKnownTarget),]
sort(table(KnownTarget_predictions$MaxTargetName[which(drugs_wdBoth_interaction_andTrueKnownTarget)]))
# saveRDS(drugCandidates_for_secTargets, '../data/drugCandidates_for_secTargets.RDS')
# saveRDS(KnownTarget_predictions, '../Data/KnownTarget_predictions.RDS')
# KnownTarget_predictions=readRDS('../Data/KnownTarget_predictions.RDS')
```

```{r}
KnownTarget_predictions$Maxcorr=sapply(1:nrow(KnownTarget_predictions), function(x)
  err_handle(drugVScrispr_corr_Strength[KnownTarget_predictions$MaxTargetName[x],
                                        KnownTarget_predictions$drugBroadID[x]]) )
```

