---
title: "Data curation and saving"
output: html_document
date: "2022-08-28"
---
<!-- Libraries -->
```{r}
require(data.table)
require('stringb')
require(parallel)
require('tictoc')

#Functions needed
source('../3.Tools/myCustom_functions.R')
```

<!-- Reading Data -->
```{r}
onTarget=readRDS('../Data/onTarget_v2.0.RDS')
```


<!-- Run correlation btw all crispr vs all drugs -->
```{r}
## finding the commom cellines between the CRISPR and drug screen
common_cellLines=intersect(colnames(onTarget$avana_22Q2),colnames(onTarget$secondary_prism))

## extracting names of all drugs and genes
all_genenames=rownames(onTarget$avana_22Q2)
all_drugNames=rownames(onTarget$secondary_prism)

## Running the function to find correlation between all crispr vs all drugs
tic()
drugVScrispr_corr_features_list=mclapply(all_drugNames,
                                         function(x) correlation_bet_crispr_drug(x), mc.cores = detectCores())
names(drugVScrispr_corr_features_list)=all_drugNames
toc()
```

```{r}
## Save RDS file
saveRDS(drugVScrispr_corr_features_list,
        '../Data/drugVScrispr_corr_features_list.RDS')
```

<!-- known target prediction-->
```{r}
## list of correlation stregth of all genes
drugVScrispr_corr_Strength=sapply(drugVScrispr_corr_features_list, function(x) x[,2])

drugSubset_map2_annotation <- match(rownames(onTarget$secondary_prism), onTarget$drugCategory$broad_id_trimmed)

all_drugNames_common = onTarget$drugCategory$name[drugSubset_map2_annotation]
all_drugTargets = onTarget$drugCategory[drugSubset_map2_annotation,c('name','target')]
all_drugMOA = onTarget$drugCategory$moa[drugSubset_map2_annotation]
```


<!-- Identify the known target Correlation -->
```{r}
all_drugTargets_seperated = str_split(as.character(all_drugTargets), ", ")

all_drugTargets_correlation=sapply(1:length(all_drugTargets_seperated),
      function(x) {
        ret_cor=drugVScrispr_corr_Strength[
          match(all_drugTargets_seperated[[x]],
                rownames(drugVScrispr_corr_Strength)), x]
        names(ret_cor)=err_handle(all_drugTargets_seperated[[x]])
        ret_cor
        } )

names(all_drugTargets_correlation) <- as.character(all_drugNames_common)
all_drugTargets_correlation['dabrafenib']

### Dataframe of the knowntarget_prediction
all_drugTargets_MAXcorrelation=sapply(all_drugTargets_correlation, function(x) max(x, na.rm=T))
all_drugTargets_MAXcorrGene=sapply(all_drugTargets_correlation,
                                      function(x) names(which.max(x)))
all_drugTargets_MAXcorrGene[sapply(all_drugTargets_MAXcorrGene, length)==0]=NA
KnownTarget_predictions=data.frame(
  drugName=names(all_drugTargets_MAXcorrelation),
  MaxTargetName=unlist(all_drugTargets_MAXcorrGene),
  Maxcorr=all_drugTargets_MAXcorrelation)
KnownTarget_predictions=KnownTarget_predictions[order(KnownTarget_predictions$Maxcorr, decreasing = T),]
```

```{r}
## Save RDS file
saveRDS(KnownTarget_predictions,
        '../Data/KnownTarget_predictions_v0.RDS')
```


