---
title: "Interaction with expression"
output: html_document
---
<!--libraries-->
```{r}
require(ggplot2)
library(interactions)
library(ggpubr)

# # Files
setwd('/Users/neelamf2/Documents/GitHub/drug.OnTarget/data/')
source('/Users/neelamf2/Documents/GitHub/Roboust_biomarker_using_SCRNA/code/step_0_global_func.R')
source('/Users/neelamf2/Documents/GitHub/Roboust_biomarker_using_SCRNA/code/step_00_myCustom_functions.R')
```


<!--loading correlation data of drug_response and viability-->
```{r}
correlation_mat_df= read.csv("../data/correlation_matV1.csv", row.names = 1)
head(correlation_mat_df)
```

<!--To check whether the true target is dependent on the expression of the specific gene target-->
```{r}
####
cmat_drug_name= rownames(correlation_mat_df)
cmat_target= correlation_mat_df$Target

lm_cmat_with_intraction= data.frame(t(sapply(cmat_drug_name,function (x) 
    summary(lm(drug_response_with_common_celline[x,]~ crispr_with_common_celline[correlation_mat_df[x ,'Target'],]*
         expression_with_common_celline[correlation_mat_df[ x ,'Target'],] ))$coefficients[4,c(1,4)])))

colnames(lm_cmat_with_intraction)[c(1,2)]= c('intraction_estimate', 'pvalue')
lm_cmat_with_intraction$Target= correlation_mat_df$Target
summary(lm_cmat_with_intraction$intraction_estimate)
lm_cmat_with_intraction$intraction_estimate[1]
mean(lm_cmat_with_intraction$intraction_estimate)
```

```{r}
ggplot(lm_cmat_with_intraction, aes(x=intraction_estimate))+
  geom_histogram()
```

<!--interaction of CDK9 (TG-02)-->
```{r}
# lm_cmat_with_intraction$name_common=onTarget$drugCategory$name[match(rownames(lm_cmat_with_intraction), onTarget$drugCategory$broad_id_trimmed)]
# lm_cmat_with_intraction[order(lm_cmat_with_intraction$intraction_estimate, decreasing = T),]
# lm_cmat_with_intraction[grep("TG-02",(lm_cmat_with_intraction$name_commo), ignore.case = T),]
# 
# correlation_mat_df$name_commom= onTarget$drugCategory$name[match(rownames(correlation_mat_df), onTarget$drugCategory$broad_id_trimmed)]
# correlation_mat_df[grep("TG-02",(correlation_mat_df$name_commom), ignore.case = T),]
# # write.csv(lm_cmat_with_intraction, "../data/interaction_coffientsV1.csv")
```
<!-- intraction for quantile-->
```{r}
# lm_cmat_with_intractionQ= data.frame(t(sapply(cmat_drug_name,function (x) 
#     summary(lm(drug_response_with_common_celline[x,]~ crispr_with_common_celline[correlation_mat_df[ x ,'Target'],]*
#          xtile(expression_with_common_celline[correlation_mat_df[ x ,'Target'],], 3) ))$coefficients[4,c(1,4)])))
# 
# colnames(lm_cmat_with_intractionQ)[c(1,2)]= c('intraction_estimate', 'pvalue')
# lm_cmat_with_intractionQ$Target= correlation_mat_df$Target
# summary(lm_cmat_with_intractionQ$intraction_estimate)
# lm_cmat_with_intractionQ$intraction_estimate[1]
# mean(lm_cmat_with_intractionQ$intraction_estimate)
```

<!--Example interaction Plot with ibrutin (Target - BTK)-->
```{r}
drug_cat[grep('ibru', drug_cat$name),]

x= 'K70301465'
drug_response= drug_response_with_common_celline[x,]
viability= crispr_with_common_celline[correlation_mat_df[ x ,'Target'],]
exp = expression_with_common_celline[correlation_mat_df[ x ,'Target'],]
expQ= exp>1
fit = lm(drug_response ~ viability * expQ)
summary(fit)

require(statar)
#### intraction plot
interact_plot(model = fit, 
              pred = viability, 
              modx = expQ,
              interval = F,
            int.width = 0.95
            # ,
            # linearity.check = TRUE
            )+ theme_bw()
```
<!-- correlation between the (correlation of drug response and viabilty) and (the coffients of interaction term)  -->
```{r}
match_rows= match(rownames(lm_cmat_with_intraction),rownames(correlation_mat_df))
cor.test(correlation_mat_df[match_rows,'cor_estimate'],(lm_cmat_with_intraction[match_rows,'intraction_estimate']))

df2plot= data.frame(cor_estimate=correlation_mat_df$cor_estimate,
                    intraction_estimate= lm_cmat_with_intraction$intraction_estimate,
                    pvalue=lm_cmat_with_intraction$pvalue,  
                    row.names = rownames(correlation_mat_df))

ggplot(df2plot, aes(x=intraction_estimate, y= (cor_estimate), color= (pvalue < 0.05)))+
  geom_point(size=1, shape= 22)+
  geom_smooth(method = "lm", se= F)+
  stat_cor()
```
<!--To check whether the true target is dependent on the expression of the specific gene target with threshold
1) threshold_1 = expression < 1
2) top 10 percent and bottom 10 percent-->
```{r}
expression_Thr=1
lm_cmat_with_intraction_with_th= as.data.frame(do.call(rbind, sapply(cmat_drug_name,function (x) 
    err_handle(
      summary(lm(drug_response_with_common_celline[x,]~ crispr_with_common_celline[correlation_mat_df[x ,'Target'],]*
         (expression_with_common_celline[correlation_mat_df[ x ,'Target'],] > expression_Thr)))$coefficients[4,c(1,4)] )))) 

colnames(lm_cmat_with_intraction_with_th)[c(1,2)]= c('intraction_estimate', 'pvalue')
lm_cmat_with_intraction_with_th$Target= correlation_mat_df$Target
lm_cmat_with_intraction_with_th= na.omit(lm_cmat_with_intraction_with_th)

summary(lm_cmat_with_intraction_with_th$intraction_estimate)
lm_cmat_with_intraction_with_th$intraction_estimate[1]
mean(lm_cmat_with_intraction_with_th$intraction_estimate)
```
```{r}
match_rows= match(rownames(lm_cmat_with_intraction_with_th), rownames(correlation_mat_df))

cor.test(correlation_mat_df[match_rows,'cor_estimate'],(lm_cmat_with_intraction_with_th[,'intraction_estimate']))

df2plot_1= data.frame(cor_estimate=correlation_mat_df[match_rows,'cor_estimate'],
                    intraction_estimate= lm_cmat_with_intraction_with_th[,'intraction_estimate'],
                    pvalue=lm_cmat_with_intraction_with_th$pvalue,  
                    row.names = rownames(lm_cmat_with_intraction_with_th))
```

```{r}
ggplot(df2plot_1, aes(x=intraction_estimate, y= (cor_estimate)))+
  geom_point(size=1, shape= 22, aes(color= pvalue < 0.05) )+
  geom_smooth(method = "lm", se= F)+
  stat_cor()
```
<!-- Finding best correlation bet pvalue of interaction term and (corr of crispr and drug resoponse) -->
```{r}
ggplot(na.omit(df2plot_1), aes(x=-log10(pvalue), y= (cor_estimate)))+
  geom_point(size=1, shape= 22, aes(color= (intraction_estimate > 0)))+
  geom_smooth(method = "lm", se= F)+
  stat_cor(label.y.npc = "top")
```

<!--filtering the drug target pair with positive interaction and pvalue > th-->
```{r}
p_th= 0.05
df2plot_1$cor_estimateQ=factor(xtile(df2plot_1$cor_estimate, 5))
df2plot_1$log10P= -log10(df2plot_1$pvalue)
df2plot_1$conditionOFInterest=df2plot_1$pvalue <p_th & df2plot_1$intraction_estimate >0
aggregate_df2plot_1=aggregate(df2plot_1$conditionOFInterest, list(df2plot_1$cor_estimateQ), function(x) sum(x)/length(x))
colnames(aggregate_df2plot_1)=c('corEstimate', 'Conditions_matched_Proportion')
ggplot(aggregate_df2plot_1, aes(y=Conditions_matched_Proportion, x=corEstimate))+
  geom_bar(stat = 'identity')+
  theme_bw(base_size = 15)
```
<!--Adding the drug name and target name to the dataset-->
```{r}
# df2plot_1=df2plot_1[order(df2plot_1$pvalue),]
df2plot_1=df2plot_1[order(df2plot_1$cor_estimate),]
df2plot_1$drugName=onTarget$drugCategory$name[match(row.names(df2plot_1), 
                                                    onTarget$drugCategory$broad_id_trimmed)]
df2plot_1$all_Target=onTarget$drugCategory$target[match(row.names(df2plot_1), 
                                                        onTarget$drugCategory$broad_id_trimmed)]
df2plot_1$Target=correlation_mat_df$Target[match(row.names(df2plot_1), 
                                                 rownames(correlation_mat_df))]

filtered_df2= df2plot_1[df2plot_1$pvalue < p_th & df2plot_1$intraction_estimate >0,]
table(filtered_df2$Target)
```

<!-- Whether the correlation estimate is better for single targets vs multiple targets
 1) when adding all the targets of the drug of interest-->
```{r}
df2plot_1$N_Target=sapply(df2plot_1$all_Target, function(x) 
  length(strsplit(as.character(x), ', ')[[1]]))
df2plot_1$N_Target_capped=df2plot_1$N_Target
df2plot_1$N_Target_capped[df2plot_1$N_Target>5]=5


## ploting the box plot of cor_estimate of drug response and viabilty by the number of the target.
ggplot(df2plot_1, aes(x=factor(N_Target_capped), y=cor_estimate))+
  geom_boxplot()+
  theme_bw(base_size = 15)
```
<!--cellines greater than th-->
```{r}
match(filtered_df2$Target, rownames(expression_with_common_celline))
numbers_of_cellines= expression_with_common_celline[match(filtered_df2$Target, rownames(expression_with_common_celline)), ]

dim(numbers_of_cellines)
exp_data_with_th= sapply(filtered_df2$Target, function (x) 
  expression_with_common_celline[x,expression_with_common_celline[x,] > expression_Thr])
sum_cellines_wherw_exp_th_is_true= sapply(seq(1:length(filtered_df2$Target)), function (x) length(exp_data_with_th[[x]]))

df2plot_3= data.frame(targets= filtered_df2$Target, 
                      cellines_expressed= sum_cellines_wherw_exp_th_is_true,
                      drugName= filtered_df2$drugName
                      )
df2plot_3$cellines_not_expressed = 322- df2plot_3$cellines_expressed

ggplot(df2plot_3, aes(x= reorder(drugName,cellines_expressed, decreasing = T), y= cellines_expressed, fill=targets))+
  geom_bar(stat = 'identity')+
  theme_bw(base_size = 12)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab('Number of cellines where expression /n
       is greter than 2')+
  xlab('Drug Name')
```

```{r}
ggplot(df2plot_3, aes(x= reorder(drugName,cellines_not_expressed, decreasing = T), y= cellines_not_expressed, fill=targets))+
  geom_bar(stat = 'identity')+
  theme_bw(base_size = 12)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab('Number of cellines where expression /n
       is less than 1')+
  xlab('Drug Name')
```

