---
title: "R Notebook"
output: html_notebook
---

<!-- Identify secondary targets -->
```{r}
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
```
<!-- Step 1: Characterize drugs where secondary targets could be identified -->
```{r}
#known targets
hist(onTarget$expression_20Q4)
  unique(drugCandidates_for_secTargets$drugName)
sort(table(drugCandidates_for_secTargets$MaxTargetName))
#Drug names
drugCandidates_for_secTargets$drugName
#Drug Ranks
drugCandidates_for_secTargets$PredictedRank
```

```{r}
drugCandidates_for_secTargets_ordered=unique(drugCandidates_for_secTargets[order(drugCandidates_for_secTargets$interaction_strength),])
```

```{r}
drugCandidates_for_secTargets_ordered
```

<!-- Visualize for an example interaction-->
```{r}
### ask sanju to provide the updated file for the secondary target
candidate_drug_target_pair=drugCandidates_for_secTargets_ordered[17,]
cand_drugName=candidate_drug_target_pair$drugName
cand_Targetname=candidate_drug_target_pair$MaxTargetName
cand_drugBroadID=candidate_drug_target_pair$drugBroadID
```
<!-- Variables from Step 2 -->
```{r}
infunc_drug_matched=err_handle(drug_matched[cand_drugBroadID,])
infunc_avana_matched=err_handle(avana_matched[cand_Targetname,])
infunc_expression_matched=err_handle(expression_matched[cand_Targetname,]<2)
lm_model=lm(infunc_drug_matched ~
                infunc_avana_matched*infunc_expression_matched)
err_handle(summary(lm_model)$coefficients[4,c(1,4)])
interact_plot(lm_model, pred = infunc_avana_matched, modx = infunc_expression_matched)
```

```{r}
CellLinesWD_Target_low_expression=names(which(infunc_expression_matched))
Identify_secondary_Target_list <- function(infunc_cellLines=CellLinesWD_Target_low_expression,
                                           infunc_drugBroadID=cand_drugBroadID){
  infunc_drug_matched=err_handle(drug_matched[infunc_drugBroadID,infunc_cellLines])
  infunc_avana_matched=err_handle(avana_matched[,infunc_cellLines])
  correlation_df=sapply(1:nrow(infunc_avana_matched),function(x)
    unlist(cor.test_trimmed_v0.default(infunc_drug_matched, infunc_avana_matched[x,])))
  correlation_df=t(correlation_df)
  row.names(correlation_df) <- rownames(infunc_avana_matched)
  correlation_df
}
```

```{r}
secTargets_example=Identify_secondary_Target_list(infunc_cellLines=CellLinesWD_Target_low_expression,
                               infunc_drugBroadID=cand_drugBroadID)
secTargets_example_df=as.data.frame(secTargets_example)
secTargets_example_df_ordered=secTargets_example_df[order(secTargets_example_df$estimate.cor, decreasing = T),]
secTargets_example_df_ordered$FDR=fdrcorr(secTargets_example_df_ordered$p.value)
secTargets_example_df_ordered$rank=1:nrow(secTargets_example_df_ordered)
secTargets_example_df_ordered
secTargets_example_df_ordered['CDK4',]
```


```{r}
secTargets_example_df_ordered[cand_Targetname,]
# secTargets_example_df_ordered[c('BRAF', 'RAF1', 'SIK1', 'NEK11', 'LIMK1'),]
```


```{r}
drug_matched[cand_drugBroadID,CellLinesWD_Target_low_expression]
```
```{r}
onTarget$drugCategory[grep(cand_drugBroadID,onTarget$drugCategory$broad_id_trimmed),]
```
```{r}
secTargets_example=Identify_secondary_Target_list(infunc_cellLines=colnames(avana_matched),
                               infunc_drugBroadID=cand_drugBroadID)
secTargets_example_df=as.data.frame(secTargets_example)
secTargets_example_df_ordered=secTargets_example_df[order(secTargets_example_df$estimate.cor, decreasing = T),]
secTargets_example_df_ordered$FDR=fdrcorr(secTargets_example_df_ordered$p.value)
secTargets_example_df_ordered$rank=1:nrow(secTargets_example_df_ordered)
secTargets_example_df_ordered
```