---
title: "Data, libraries and preprocessing"
output: html_notebook
---

<!-- Atomic inputs needed to run a code -->
<!-- Libraries -->
```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("fgsea")

### network problem : talked to narisu and talked about the authentication
# library(fgsea)
require(data.table)
require('stringb')
require(parallel)
require('tictoc')
require(statar)
require('interactions')
require(stats)
require(reshape2)
require(ggplot2)
require(ggpubr)
require(ggrepel)
require(ggforce)
require(grid)
require(cowplot)
require(gridExtra)
require(pROC)
require(DEGreport)

#Functions needed
source('../3.Tools/myCustom_functions.R')
```
<!-- OnTarget Data and the preprocessing-->
```{r}
# setwd('/Users/sinhanee/Documents/projects/drug.OnTarget/')
onTarget=readRDS('../Data/onTarget_v2.0.RDS')
KnownTarget_predictions=readRDS('../Data/KnownTarget_predictions_v3.RDS') ## required dataset latest version
drugCandidates_for_secTargets=readRDS('../Data/drugCandidates_for_secTargets.RDS')
drugVScrispr_corr_features_list=readRDS('../Data/drugVScrispr_corr_features_list.RDS')
```

<!-- Get the correlation strength, P value and the rank of the correlation matrix-->
```{r}
drugVScrispr_corr_Strength=sapply(drugVScrispr_corr_features_list, function(x) x[,2])
corrMat_P=sapply(drugVScrispr_corr_features_list, function(x) x[,1])
corrMat=drugVScrispr_corr_Strength
corrMat_rank=apply(-corrMat, 2, rank)
```
<!-- known target prediction-->
```{r}
drugSubset_map2_annotation <- match(rownames(onTarget$secondary_prism), onTarget$drugCategory$broad_id_trimmed)

all_drugNames_common = onTarget$drugCategory$name[drugSubset_map2_annotation]
all_drugTargets = onTarget$drugCategory[drugSubset_map2_annotation,c('name','target')]
all_drugMOA = onTarget$drugCategory$moa[drugSubset_map2_annotation]
```


<!-- Identify the known target Correlation -->
```{r}
all_drugTargets_seperated = str_split(as.character(all_drugTargets), ", ")

all_drugTargets_correlation=sapply(1:length(all_drugTargets_seperated),
      function(x) {
        ret_cor=drugVScrispr_corr_Strength[
          match(all_drugTargets_seperated[[x]],
                rownames(drugVScrispr_corr_Strength)), x]
        names(ret_cor)=err_handle(all_drugTargets_seperated[[x]])
        ret_cor
        } )

names(all_drugTargets_correlation) <- as.character(all_drugNames_common)
all_drugTargets_correlation['dabrafenib']

### Dataframe of the knowntarget_prediction
all_drugTargets_MAXcorrelation=sapply(all_drugTargets_correlation, function(x) max(x, na.rm=T))
all_drugTargets_MAXcorrGene=sapply(all_drugTargets_correlation,
                                      function(x) names(which.max(x)))
all_drugTargets_MAXcorrGene[sapply(all_drugTargets_MAXcorrGene, length)==0]=NA
KnownTarget_predictions=data.frame(
  drugName=names(all_drugTargets_MAXcorrelation),
  MaxTargetName=unlist(all_drugTargets_MAXcorrGene),
  Maxcorr=all_drugTargets_MAXcorrelation)
KnownTarget_predictions=KnownTarget_predictions[order(KnownTarget_predictions$Maxcorr, decreasing = T),]
```


<!-- Preprocessing of Drug Category Data set to identify drug is inhibitor or not -->
<!-- Compute if a drug is inhibitor or not -->
<!--  Note: tell the activator part to sanju is.activator ~1640 due to grep(agonist), is.activator.check ~800. -->
```{r}
onTarget$drugCategory = onTarget$drugCategory %>% dplyr::mutate(is.inhibitor = ifelse(grepl('inhibitor', onTarget$drugCategory$moa) |
                                                                   grepl('antagonist', onTarget$drugCategory$moa) |
                                                                   grepl('blocker', onTarget$drugCategory$moa) ,TRUE, FALSE),
                                     is.activator = ifelse(grepl('activator', onTarget$drugCategory$moa) |
                                                                   grepl('\\bagonist\\b', onTarget$drugCategory$moa) |
                                                                   grepl('stimulant', onTarget$drugCategory$moa) ,TRUE, FALSE))
```

<!-- MATCHED MATRIX for expression data for Step_2 interaction of expression and mutation data-->
```{r}
matched_cellLines=Reduce(intersect,
                         list(colnames(onTarget$expression_20Q4),
                              colnames(onTarget$avana_22Q2),
                              colnames(onTarget$secondary_prism)))
expression_matched=onTarget$expression_20Q4[,matched_cellLines]
avana_matched=onTarget$avana_22Q2[,matched_cellLines]
drug_matched=onTarget$secondary_prism[,matched_cellLines]
```
