---
title: "Data curation of Known target prediction with correlation between the crispr KO and the Drug response"
output: html_document
date: "2022-08-28"
---


<!-- Data curation of Known target prediction file. First we compute the correlation between the crispr KO and the Drug response. using the corr strenth, the p value and rank, we created the variables such as  -->
<!-- MaxtargetName: if a drug have multiple target, what is the best target which have best correlation. -->
<!-- Maxcorr: The respective correlation stregth of the drug target pair. -->


<!-- Libraries -->
```{r}
require(data.table)
require('stringb')
require(parallel)
require('tictoc')
require(tidyr)
library(tidyverse)

#Functions needed
source('../myCustom_functions.R')
```

<!-- loading on On true Target file -->
```{r}
onTarget=readRDS('../../Data/onTarget_v2.0.RDS')
```

<!-- Run correlation btw all crispr vs all drugs -->
```{r}
## finding the commom cellines between the CRISPR and drug screen
common_cellLines=intersect(colnames(onTarget$avana_22Q2),colnames(onTarget$secondary_prism))

## extracting names of all drugs and genes
all_genenames=rownames(onTarget$avana_22Q2)
all_drugNames=rownames(onTarget$secondary_prism)

## Running the function to find correlation between all crispr vs all drugs
tic()
drugVScrispr_corr_features_list=mclapply(all_drugNames,
                                         function(x) correlation_bet_crispr_drug(x), mc.cores = detectCores())
names(drugVScrispr_corr_features_list)=all_drugNames
toc()
```

```{r}
## Save RDS file
# saveRDS(drugVScrispr_corr_features_list,
#         '../Data/drugVScrispr_corr_features_list.RDS')
```

<!-- Defining the cormat strength, Pvalue and the rank to save in known target prediction-->
```{r}
## list of correlation stregth of all genes
drugVScrispr_corr_Strength=sapply(drugVScrispr_corr_features_list, function(x) x[,2])
drugVScrispr_corr_Strength=sapply(drugVScrispr_corr_features_list, function(x) x[,2])
corrMat_P=sapply(drugVScrispr_corr_features_list, function(x) x[,1])
corrMat=drugVScrispr_corr_Strength
corrMat_rank=apply(-corrMat, 2, rank)
```

<!-- Finding commom drug target pair from avana and seconadary prism-->
```{r}
drugSubset_map2_annotation <- match(rownames(onTarget$secondary_prism), onTarget$drugCategory$broad_id_trimmed)
all_drugNames_common = onTarget$drugCategory$name[drugSubset_map2_annotation]
all_drugTargets = onTarget$drugCategory[drugSubset_map2_annotation,c('name','target')]
all_drugMOA = onTarget$drugCategory$moa[drugSubset_map2_annotation]
```

<!-- Identify the known target Correlation -->
```{r}
all_drugTargets_seperated = str_split(as.character(all_drugTargets$target), ", ")

all_drugTargets_correlation=sapply(1:length(all_drugTargets_seperated),
      function(x) {
        ret_cor=drugVScrispr_corr_Strength[
          match(all_drugTargets_seperated[[x]],
                rownames(drugVScrispr_corr_Strength)), x]
        names(ret_cor)=err_handle(all_drugTargets_seperated[[x]])
        ret_cor
        } )

names(all_drugTargets_correlation) <- as.character(all_drugNames_common)
all_drugTargets_correlation['dabrafenib']

### Dataframe of the knowntarget_prediction
all_drugTargets_MAXcorrelation=sapply(all_drugTargets_correlation, function(x) max(x, na.rm=T))
all_drugTargets_MAXcorrGene=sapply(all_drugTargets_correlation,
                                      function(x) names(which.max(x)))
all_drugTargets_MAXcorrGene[sapply(all_drugTargets_MAXcorrGene, length)==0]=NA
KnownTarget_predictions=data.frame(
  drugName=names(all_drugTargets_MAXcorrelation),
  MaxTargetName=unlist(all_drugTargets_MAXcorrGene),
  Maxcorr=all_drugTargets_MAXcorrelation)
KnownTarget_predictions=KnownTarget_predictions[order(KnownTarget_predictions$Maxcorr, decreasing = T),]
KnownTarget_predictions$drugBroadID = onTarget$drugCategory$broad_id_trimmed[match(KnownTarget_predictions$drugName, onTarget$drugCategory$name)]
```

<!-- ## addition columns requred in the data curation of KnownTarget_predictions from cormat -->
```{r}
#best Hit name
BestTargetName=apply(corrMat[,match(KnownTarget_predictions$drugBroadID, colnames(corrMat))],
                                      2, function(x) rownames(corrMat)[which.max(x)] )
BestTargetName[sapply(BestTargetName, length)==0]=NA
KnownTarget_predictions$BestTargetName=unlist(BestTargetName)

#best hit score
BestTargetCorr=apply(corrMat[,match(KnownTarget_predictions$drugBroadID, colnames(corrMat))],
                                      2, function(x) max(x, na.rm = T) )
KnownTarget_predictions$BestTargetCorr=BestTargetCorr

# Best Hit Significance
KnownTarget_predictions$BestTargetCorrP = sapply(1:nrow(KnownTarget_predictions), function(x) 
  err_handle(corrMat_P[KnownTarget_predictions[x,'BestTargetName'], KnownTarget_predictions[x,'drugBroadID']]) ) 

# Known Target Significance
KnownTarget_predictions$KnownTargetCorrP = sapply(1:nrow(KnownTarget_predictions), function(x) 
  err_handle(corrMat_P[KnownTarget_predictions[x,'MaxTargetName'], KnownTarget_predictions[x,'drugBroadID']]) ) 

corrMat_FDR=apply(corrMat_P, 2, function(x) fdrcorr(x))
# Best Hit Significance - FDR corrected
KnownTarget_predictions$BestTargetCorrFDR = sapply(1:nrow(KnownTarget_predictions), function(x) 
  err_handle(corrMat_FDR[KnownTarget_predictions[x,'BestTargetName'], KnownTarget_predictions[x,'drugBroadID']]) ) 
# Known Target Significance - FDR corrected
KnownTarget_predictions$KnownTargetCorrFDR = sapply(1:nrow(KnownTarget_predictions), function(x) 
  err_handle(corrMat_FDR[KnownTarget_predictions[x,'MaxTargetName'], KnownTarget_predictions[x,'drugBroadID']]) ) 

saveRDS(KnownTarget_predictions, '../../Data/KnownTarget_predictions.RDS')
```

```{r}
KnownTarget_predictions_v3=readRDS('../Data/KnownTarget_predictions_v3.RDS') ## required dataset latest version
KnownTarget_predictions_v3= KnownTarget_predictions_v3[order(KnownTarget_predictions_v3$Maxcorr, decreasing = T),]
```




