---
title: "Pathway enrichment test and data curation"
output: html_notebook
---

# Creating the Pathway enrichment dataset to further produce the figure (supplementary figure 3 and 7)

```{r}
knitr::knit('../3.Tools/Step0_Write_Functions.Rmd')
knitr::knit('../3.Tools/Step0B_Data_and_Libraries.Rmd')
library(fgsea)
library(ggforce)
library(tidyverse)
theme_set(theme_bw(18))
```

<!-- MOA pathway annotation -->
```{r}
target_by_moa=split(onTarget$drugCategory$target, onTarget$drugCategory$moa)
target_by_moa_unlisted=sapply(target_by_moa, unlist)

target_by_moa_pathways=lapply(target_by_moa_unlisted, function(y){
  unique(unlist(sapply(as.character(y), function(x)
  unlist(strsplit(x, ', ')) )))
}
)
moa_pathways=target_by_moa_pathways
saveRDS(moa_pathways,'../data/moa_pathways.RDS' )
```
<!-- Load pathway annotation data and perform the needed preprocessing -->
```{r}
moa_pathways=readRDS('../data/moa_pathways.RDS')

moa_pathways=sapply(moa_pathways, na.omit)
hist(sapply(moa_pathways, length))
```
<!-- Run gene enrichment (this will take some time, ~20 mins) -->
```{r}
tic()
gsea_enrichment_all_drugs=mclapply(1:ncol(drugVScrispr_corr_Strength), function(x) {
  IF_corr_with_gene=unlist(drugVScrispr_corr_Strength[,x])
  names(IF_corr_with_gene)  = rownames(drugVScrispr_corr_Strength)
  IF_corr_with_gene_ordered=sort(IF_corr_with_gene, decreasing = T)

  gsea_enrichment=fgsea(pathways = moa_pathways,
                  stats = IF_corr_with_gene_ordered,
                  minSize=1,
                  maxSize=100)
  gsea_enrichment
}, mc.cores = detectCores())
toc()
names(gsea_enrichment_all_drugs)=colnames(drugVScrispr_corr_Strength)
saveRDS(gsea_enrichment_all_drugs, '../data/gsea_enrichment_all_drugs.RDS')
```


