---
title: "Viagra_drug_target_rank_test"
output: html_document
---
<!-- Libraries -->
```{r}
library(ggrepel)
install.packages("gridExtra")
library("gridExtra")
```

<!--Data loading and exploration-->
```{r}
## Drug response viability
onTarget=readRDS('/Users/neelamf2/Documents/GitHub/drug.OnTarget/data/onTarget_v12.RDS')
```

<!--sildenafil drug target-->
```{r}
onTarget$drugCategory[grep('sildenafil',onTarget$drugCategory$name, ignore.case = T),]

DOI_id = grep('sildenafil',onTarget$drugCategory$name, ignore.case = T)
DOI_broadid = onTarget$drugCategory$broad_id_trimmed[DOI_id]

DOI_response=onTarget$drug_prism["K79759585",]
hist(DOI_response)
```

<!--Running Ontarget pipeline to find what are the top hits and rank of "PDE5A"-->
```{r}
crispr_matched=colSubset(mat =onTarget$avana, column_Names =  names(DOI_response))
DOI_response_matched=DOI_response[colnames(crispr_matched)]

correlations_with_a_gene=apply(crispr_matched, 1, function(x)
  unlist(cor.test(x, DOI_response_matched)[c(3,4)]))

correlations_with_a_gene=as.data.frame(t(correlations_with_a_gene))
correlations_with_a_gene=correlations_with_a_gene[order(correlations_with_a_gene$estimate.cor, decreasing = T),]
correlations_with_a_gene$rank=seq(1:nrow(correlations_with_a_gene))
correlations_with_a_gene$fdr_pvalue= fdrcorr(correlations_with_a_gene$p.value)
correlations_with_a_gene
# write.csv(correlations_with_a_gene, "../Correlation_df_with_viagra.csv")
```
<!-- Scatter plot showing the top hits predicted via our pipeline -->
```{r}
Plot_1_df_rank= correlations_with_a_gene

Plot_1= ggplot(Plot_1_df_rank, aes(x=rank, 
                                  y= estimate.cor, 
                                  color= p.value< 0.05 & estimate.cor > 0))+
  geom_point(stat="identity", aes(size= -rank),show.legend = F)+
  geom_text(aes(label=ifelse(rank == 1,as.character(rownames(Plot_1_df_rank)),'')),hjust = 0, nudge_x = 1000, nudge_y = 0.001,size= 4)+
  theme_bw(base_size = 18)+
  labs(x= 'Rank of gene target', 
       y='Target confidence score' 
       # ,title= 'Ranks of suggested targets of sildenafil in pan cancer'
       )+
  theme(legend.position = 'bottom')

ggsave('../result/Scatter_plot_showing_rank_of_all_targets.pdf', Plot_1,
       height=6, width = 8, units = 'in')
```

<!--Finding rank of "PDE5A" and other PDE's in the cor result from our pipeline-->
```{r}
pde_correlation= correlations_with_a_gene[grep('^PDE',rownames(correlations_with_a_gene)),]

Plot_3= ggplot(pde_correlation, aes(x= reorder(rownames(pde_correlation), estimate.cor), 
                                  y= estimate.cor, 
                                  color= p.value< 0.05))+
  geom_point(stat="identity", aes(size= -rank),show.legend = F)+
  geom_text(aes(label=ifelse(rank < 500,as.character(rank),'')), hjust = 0, nudge_x = -1.6, nudge_y = 0.0001,size= 4)+
  theme_bw(base_size = 15)+ 
  theme(legend.position = 'top', axis.text.x = element_text(angle = 90))+
  labs(x= 'Rank of gene target', 
       y='Target confidence score'
       # ,title= 'Ranks of suggested targets of sildenafil in pan cancer'
       )

ggsave('../result/Scatter_plot_showing_rank_of_all_PDE.jpg', Plot_3,
       height=6, width = 8, units = 'in')

# write.csv(pde_correlation, "../neelamf2/Documents/GitHub/drug.OnTarget/data/PDE_correlation.csv")
```
<!-- Visualization of all targets of viagra -->
```{r}
DOI_list=c('PDE5A', "PDE6G", "PDE6H", "SLCO1B1", 'SLCO1B3')
predicted_rank_of_targets_of_viagra= correlations_with_a_gene[DOI_list,]
predicted_rank_of_targets_of_viagra$fdr_pvalue= fdrcorr(predicted_rank_of_targets_of_viagra$p.value)

Plot_2 = ggplot(predicted_rank_of_targets_of_viagra, aes(x=reorder(rownames(predicted_rank_of_targets_of_viagra), estimate.cor), 
                                  y= estimate.cor, 
                                  color= fdr_pvalue< 0.05))+
  geom_point(stat="identity", aes(size= -rank), show.legend = F)+
  geom_label(label = predicted_rank_of_targets_of_viagra$rank, hjust = 0, nudge_x = -0.6, nudge_y = 0.005,size= 5)+
  theme_bw(base_size = 15)+
  theme(legend.position = 'top')+
  labs(x= 'Five known targets of sildenafil (Drug bank)', 
       y='Target confidence score'
       # ,title= 'Ranks of suggested targets of sildenafil in pan cancer'
       )

ggsave('../result/point_plot_showing_rank_targets_for_viagra.jpg', Plot_2,
       height=6, width = 8, units = 'in')
```
<!-- Functionfor sildenafil -->
```{r}
### intersect of drug prism (primary) and avana
COI = intersect(colnames(onTarget$avana), colnames(onTarget$drug_prism))
cellLines_with_screens=match(COI, onTarget$annotation_20Q4$DepMap_ID)
lineages_with_enough_samples=names(table(onTarget$annotation_20Q4$lineage[cellLines_with_screens])[
  which(table(onTarget$annotation_20Q4$lineage[cellLines_with_screens])>15)])



checking_sildenafil_top_target_in_each_cancer_type <- function(infunc_cancer_type = lineages_with_enough_samples[1],
                                         infunc_DOI_broadid=DOI_broadid,
                                         infunc_COI= COI){
  infunc_cellines = onTarget$annotation_20Q4$DepMap_ID[grep(infunc_cancer_type,onTarget$annotation_20Q4$lineage, ignore.case = T)]
  infunc_cellines_matched=intersect(infunc_cellines, infunc_COI)
  #### Matrix sorted by board id
  DOI_response=onTarget$drug_prism[infunc_DOI_broadid,infunc_cellines_matched]
  crispr_matched=onTarget$avana[,infunc_cellines_matched]
  
#### Correlation of the Crispr and drug response 
  correlations_with_a_gene=apply(crispr_matched, 1, function(x)
    unlist(cor.test(x, DOI_response)[c(3,4)]))
  correlations_with_a_gene=as.data.frame(t(correlations_with_a_gene))
  correlations_with_a_gene=correlations_with_a_gene[order(correlations_with_a_gene$estimate.cor, decreasing = T),]
  correlations_with_a_gene$rank=seq(1:nrow(correlations_with_a_gene))
  correlations_with_a_gene$cancer_type = infunc_cancer_type
  correlations_with_a_gene
}

# Running the function
top_target_of_sildenafil_in_each_cancer_type= lapply(lineages_with_enough_samples, 
                                               function (x) 
                                            checking_sildenafil_top_target_in_each_cancer_type(infunc_cancer_type = x,
                                                                                                  infunc_DOI_broadid = DOI_broadid))

top_target_of_sildenafil_in_each_cancer_type[[2]]$cancer_type = "CNS"
PDE5A_correlation_sildenafil=do.call(rbind, lapply(top_target_of_sildenafil_in_each_cancer_type, function(x) 
  x[rownames(x)=='PDE5A',] ))
PDE5A_correlation_sildenafil= PDE5A_correlation_sildenafil[order(PDE5A_correlation_sildenafil$estimate.cor, decreasing = F),]
PDE5A_correlation_sildenafil$target= 'PDE5A'
PDE5A_correlation_sildenafil$fdr_pvalue= fdrcorr(PDE5A_correlation_sildenafil$p.value)
rownames(PDE5A_correlation_sildenafil)= NULL
```

```{r}
ggplot(PDE5A_correlation_sildenafil, aes(x=factor(cancer_type, levels = factor(cancer_type)), 
                                  y= estimate.cor, 
                                  color= fdr_pvalue< 0.05))+
  geom_point(stat="identity", aes(size= -rank))+
  geom_segment(aes(x= factor(cancer_type, levels = factor(cancer_type)),
                   xend = factor(cancer_type, levels = factor(cancer_type)), y=0, 
                   yend=estimate.cor))+
  geom_label(label = PDE5A_correlation_sildenafil$rank, hjust = 0, nudge_x = 0.1, nudge_y = 0.08,size= 3)+
  theme(text = element_text(size = 9),
        element_line(size =1))+
  labs(x= 'Cancer Types', 
       y='Target confidence score', 
       title= 'Rank and predicted score of PDE5A for each cancer type')
```

```{r}
FAM49B_correlation_sildenafil=do.call(rbind, lapply(top_target_of_sildenafil_in_each_cancer_type, function(x) 
  x[rownames(x)=='FAM49B',] ))
FAM49B_correlation_sildenafil= FAM49B_correlation_sildenafil[order(FAM49B_correlation_sildenafil$estimate.cor, decreasing = F),]
FAM49B_correlation_sildenafil$target= 'FAM49B'
FAM49B_correlation_sildenafil$fdr_pvalue= fdrcorr(FAM49B_correlation_sildenafil$p.value)
rownames(FAM49B_correlation_sildenafil)= NULL

# Visualization
ggplot(FAM49B_correlation_sildenafil, aes(x=factor(cancer_type, levels = factor(cancer_type)), 
                                  y= estimate.cor, 
                                  color= fdr_pvalue< 0.05))+
  geom_point(stat="identity", aes(size= -rank))+
  geom_segment(aes(x= factor(cancer_type, levels = factor(cancer_type)),
                   xend = factor(cancer_type, levels = factor(cancer_type)), y=0, 
                   yend=estimate.cor))+
  geom_label(label = FAM49B_correlation_sildenafil$rank, hjust = 0, nudge_x = 0.1, nudge_y = 0.08,size= 3)+
  theme(text = element_text(size = 12),
        element_line(size =1),
        axis.text.x = element_text(angle = 45))+
  labs(x= 'Cancer Types', 
       y='Target confidence score', 
       title= 'Rank and predicted score of FAM49B for each cancer type')

```
<!-- Focusing on lung, brest, and colon -->
```{r}
cancer_of_interest= c('lung','colorectal', 'breast')
Plot_2= rbind(PDE5A_correlation_sildenafil[PDE5A_correlation_sildenafil$cancer_type %in% cancer_of_interest,],
      FAM49B_correlation_sildenafil[FAM49B_correlation_sildenafil$cancer_type %in% cancer_of_interest,])
rownames(Plot_2) = NULL

### Visualzation <--comparing top rank target from pan cancer with PDE5A->

ggplot(Plot_2, aes(x=factor(cancer_type, levels = unique(factor(cancer_type))), 
                                  y= estimate.cor, 
                                  color= fdr_pvalue < 0.05))+
  geom_point(stat="identity", aes(size= rank))+
  geom_segment(aes(x= factor(cancer_type, levels = unique(factor(cancer_type))),
                   xend = factor(cancer_type, levels = unique(factor(cancer_type))), y=0,
                   yend=estimate.cor))+
  geom_label(label =Plot_2$rank, 
             hjust = 0.01, 
             nudge_x = 0.1, 
             nudge_y = 0.001,
             size= 3,
             aes(color = Plot_2$target))+
  theme(text = element_text(size = 12),
        element_line(size =1),
        axis.text.x = element_text(angle = 45))+
  labs(x= 'Cancer Types', 
       y='Target confidence score', 
       title= 'Rank and predicted score focusing on three cancer type')
```

```{r}
correlation_sildenafil=do.call(rbind, lapply(top_target_of_sildenafil_in_each_cancer_type, function(x) 
  x[x$rank == 1,] ))
correlation_sildenafil= correlation_sildenafil[order(correlation_sildenafil$estimate.cor, decreasing = F),]
correlation_sildenafil$target= rownames(correlation_sildenafil)
correlation_sildenafil$fdr_pvalue= fdrcorr(correlation_sildenafil$p.value)
rownames(correlation_sildenafil)= NULL

Plot_3= rbind(PDE5A_correlation_sildenafil[PDE5A_correlation_sildenafil$cancer_type %in% cancer_of_interest,],
      correlation_sildenafil[correlation_sildenafil$cancer_type %in% cancer_of_interest,])
rownames(Plot_3) = NULL

### Visualzation <--comparing top rank target and PDE5A in lung, breast, and colon->

ggplot(Plot_3, aes(x=factor(cancer_type, levels = unique(factor(cancer_type))), 
                                  y= estimate.cor, 
                                  color= fdr_pvalue<0.05))+
  geom_point(stat="identity", aes(size= rank))+
  geom_segment(aes(x= factor(cancer_type, levels = unique(factor(cancer_type))),
                   xend = factor(cancer_type, levels = unique(factor(cancer_type))), y=0,
                   yend=estimate.cor))+
  geom_label(label =Plot_3$target, hjust = 0.01, nudge_x = 0.1, nudge_y = 0.001,
             size= 3)+
  theme(text = element_text(size = 12),
        element_line(size =1),
        axis.text.x = element_text(angle = 45))+
  theme_bw(base_size = 15)+
  labs(x= 'Cancer Types', 
       y='Target confidence score', 
       title= 'Top rank and PDE5A rank in three cancer type')
```

<!-- Computing Intraction for the PDE5A -->
```{r}
#### Data frames required
avana_hulala= onTarget$avana[,COI]
dim(avana_hulala)
drug_response_hulala= onTarget$drug_prism[unique(rownames(onTarget$drug_prism)),
                                                            COI]
expression_hulala= onTarget$expression[,COI]

### Drug_category for broad_ID
Drug_OI= intersect(rownames(drug_response_hulala), onTarget$drugCategory$broad_id_trimmed)
drug_cat= onTarget$drugCategory[onTarget$drugCategory$broad_id_trimmed %in% Drug_OI,]
dim(drug_cat)

drug_name= "K79759585"

lm_cmat_with_intraction= data.frame(t(sapply(DOI_list,function (x) 
    summary(lm(drug_response_hulala[drug_name,]~ 
                 avana_hulala[x,]*
         expression_hulala[x,]))$coefficients[4,c(1,4)])))

colnames(lm_cmat_with_intraction)[c(1,2)]= c('intraction_estimate', 'pvalue')
lm_cmat_with_intraction$Target= DOI_list


lm_cmat_with_intraction$name_common=drug_cat[drug_cat$broad_id_trimmed=='K79759585','name']
lm_cmat_with_intraction[order(lm_cmat_with_intraction$intraction_estimate, decreasing = T),]
```
```{r}
hist(lm_cmat_with_intraction$intraction_estimate)

drug_response= drug_response_hulala[drug_name,]
viability= avana_hulala['FAM49B',]
exp = expression_hulala['FAM49B',]
expQ=xtile(exp, 3)
hist(exp)
length(expQ)
# natural cut off based on hist suggest 4 as cut off
# expQ= exp>3
fit = lm(drug_response ~ viability * expQ)
summary(fit) 

require(statar)
#### intraction plot
interact_plot(model = fit, 
              pred = viability, 
              modx =  expQ,
              interval = F,
            int.width = 0.95
            )+ theme_bw()
```

```{r}
K=3
expQ= factor(xtile(exp, K))
top_bottom_10th_quantile= which(expQ==1 | expQ==K)
expQ[top_bottom_10th_quantile]
# TBQ stands for top_bottom_10th_quantile
drug_response_TBQ=drug_response[top_bottom_10th_quantile]
viability_TBQ=viability[top_bottom_10th_quantile]
expQ_TBQ=expQ[top_bottom_10th_quantile]
fit = lm(drug_response_TBQ ~ viability_TBQ * expQ_TBQ)
Interaction_term=round(data.frame(summary(fit)$coefficients), 2)[4,c(1,4)]
Interaction_term
#### interaction plot
interact_plot(model = fit, 
              pred = viability_TBQ, 
              modx = expQ_TBQ,
              # modx.values = "terciles",
              interval = F,
            int.width = 0.95
            # ,
            # linearity.check = TRUE
            )+ theme_bw()+
  annotate(geom='text', label=paste('alpha=',Interaction_term$Estimate,',p=', Interaction_term$Pr...t.., sep=''),
           x=0.1, y=0.3)
```

```{r}
cancer_of_interest
PDE5A_df=data.frame(PDE5A=exp,
           lineage=onTarget$annotation_20Q4$lineage[match(names(exp), onTarget$annotation_20Q4$DepMap_ID)])
plot_4= PDE5A_df[PDE5A_df$lineage %in% cancer_of_interest,]


plot_4$lineage=as.character(plot_4$lineage)
ggplot(plot_4, aes(x= lineage, y= PDE5A, fill=lineage))+
  geom_boxplot()+
  theme_bw(base_size = 15)+
  stat_compare_means(comparisons = combn(unique(plot_4$lineage), 2, simplify = F))
```
```{r}
#Correlation between the Drug killing "Sidenafil" and target "FAM49B"
TOI= "FAM49B"
plot1_drug_kill_df=data.frame(Drug_kill= DOI_response_matched, 
           mutation= onTarget$mutations_matrix[TOI,colnames(crispr_matched)],
           expression= expression_hulala[TOI,])
ggplot(plot1_drug_kill_df, aes(x=expression, y= Drug_kill))+
  geom_point()+
  geom_smooth(method = "lm", se= F)+
  stat_cor(label.y.npc = "top")
```

```{r}
plot1_drug_kill_df$mutation=factor(plot1_drug_kill_df$mutation)
levels(plot1_drug_kill_df$mutation)= c('Not Mutated', 'Mutated')
Plot_4 = ggplot(plot1_drug_kill_df, aes(x=mutation, y= Drug_kill, fill=mutation))+
  geom_boxplot()+
  stat_compare_means()+
  theme_bw(base_size = 18)+
  labs(x= 'Mutation status of FAM49B',
       y= 'Viability after Sildenafil treatment')+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        legend.position = 'bottom')
  
ggsave('../result/correlation_with_Mutation.jpg', Plot_4,
       height=4.5, width = 4)
```

```{r}
# figure <- grid.arrange(Plot_1,Plot_4,
#              layout_matrix = rbind(c(1,1, 1,2, 2 )))
figure <- ggarrange(Plot_1,Plot_4, labels = c('A','B'), widths = c(1.25,0.75))
ggsave('../result/combined_fig_for_FAM49B.jpg', figure,
       height=6.5, width =12 )
```

```{r}
combined_fig_pde= ggarrange(Plot_2,Plot_3,labels = c('A','B'), widths = c(0.80,1.20))
ggsave('../result/combined_fig_for_PDEB.jpg', combined_fig_pde,
       height=6, width =12 )
```











